// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Abstract.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Abstract: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Int32 = 0

  var text: String = String()

  var link: String = String()

  var src: String = String()

  var un: String = String()

  var duringTime: String = String()

  var voiceMd5: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_Abstract: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Abstract"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}text\0\u{1}link\0\u{1}src\0\u{1}un\0\u{1}duringTime\0\u{1}voiceMD5\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.type) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.link) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.src) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.un) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.duringTime) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.voiceMd5) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != 0 {
      try visitor.visitSingularInt32Field(value: self.type, fieldNumber: 1)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 2)
    }
    if !self.link.isEmpty {
      try visitor.visitSingularStringField(value: self.link, fieldNumber: 3)
    }
    if !self.src.isEmpty {
      try visitor.visitSingularStringField(value: self.src, fieldNumber: 4)
    }
    if !self.un.isEmpty {
      try visitor.visitSingularStringField(value: self.un, fieldNumber: 5)
    }
    if !self.duringTime.isEmpty {
      try visitor.visitSingularStringField(value: self.duringTime, fieldNumber: 6)
    }
    if !self.voiceMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.voiceMd5, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Abstract, rhs: Tieba_Abstract) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.text != rhs.text {return false}
    if lhs.link != rhs.link {return false}
    if lhs.src != rhs.src {return false}
    if lhs.un != rhs.un {return false}
    if lhs.duringTime != rhs.duringTime {return false}
    if lhs.voiceMd5 != rhs.voiceMd5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
