// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: AdInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_AdInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var showRule: Int32 = 0

  var adType: Int32 = 0

  var adDesc: String = String()

  var adPic: String = String()

  var adURL: String = String()

  var adName: String = String()

  var portrait: String = String()

  var media: [Tieba_Media] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_AdInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AdInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}show_rule\0\u{3}ad_type\0\u{3}ad_desc\0\u{3}ad_pic\0\u{3}ad_url\0\u{3}ad_name\0\u{1}portrait\0\u{1}media\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.showRule) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.adType) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.adDesc) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.adPic) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.adURL) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.adName) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.portrait) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.media) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.showRule != 0 {
      try visitor.visitSingularInt32Field(value: self.showRule, fieldNumber: 1)
    }
    if self.adType != 0 {
      try visitor.visitSingularInt32Field(value: self.adType, fieldNumber: 2)
    }
    if !self.adDesc.isEmpty {
      try visitor.visitSingularStringField(value: self.adDesc, fieldNumber: 3)
    }
    if !self.adPic.isEmpty {
      try visitor.visitSingularStringField(value: self.adPic, fieldNumber: 4)
    }
    if !self.adURL.isEmpty {
      try visitor.visitSingularStringField(value: self.adURL, fieldNumber: 5)
    }
    if !self.adName.isEmpty {
      try visitor.visitSingularStringField(value: self.adName, fieldNumber: 6)
    }
    if !self.portrait.isEmpty {
      try visitor.visitSingularStringField(value: self.portrait, fieldNumber: 7)
    }
    if !self.media.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.media, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_AdInfo, rhs: Tieba_AdInfo) -> Bool {
    if lhs.showRule != rhs.showRule {return false}
    if lhs.adType != rhs.adType {return false}
    if lhs.adDesc != rhs.adDesc {return false}
    if lhs.adPic != rhs.adPic {return false}
    if lhs.adURL != rhs.adURL {return false}
    if lhs.adName != rhs.adName {return false}
    if lhs.portrait != rhs.portrait {return false}
    if lhs.media != rhs.media {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
