// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Advertisement.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Advertisement: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var time: Int64 = 0

  var pic: String = String()

  var picClick: String = String()

  var jumpLink: String = String()

  var advertisementID: String = String()

  var viewStatisticsURL: String = String()

  var clickStatisticsURL: String = String()

  var floatingText: String = String()

  var deeplink: String = String()

  var scheme: String = String()

  var packageName: String = String()

  var displayAdIcon: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_Advertisement: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Advertisement"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}time\0\u{1}pic\0\u{3}pic_click\0\u{3}jump_link\0\u{3}advertisement_id\0\u{3}view_statistics_url\0\u{3}click_statistics_url\0\u{3}floating_text\0\u{1}deeplink\0\u{1}scheme\0\u{3}package_name\0\u{3}display_ad_icon\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.time) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.pic) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.picClick) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.jumpLink) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.advertisementID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.viewStatisticsURL) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.clickStatisticsURL) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.floatingText) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.deeplink) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.scheme) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.displayAdIcon) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.time != 0 {
      try visitor.visitSingularInt64Field(value: self.time, fieldNumber: 1)
    }
    if !self.pic.isEmpty {
      try visitor.visitSingularStringField(value: self.pic, fieldNumber: 2)
    }
    if !self.picClick.isEmpty {
      try visitor.visitSingularStringField(value: self.picClick, fieldNumber: 3)
    }
    if !self.jumpLink.isEmpty {
      try visitor.visitSingularStringField(value: self.jumpLink, fieldNumber: 4)
    }
    if !self.advertisementID.isEmpty {
      try visitor.visitSingularStringField(value: self.advertisementID, fieldNumber: 5)
    }
    if !self.viewStatisticsURL.isEmpty {
      try visitor.visitSingularStringField(value: self.viewStatisticsURL, fieldNumber: 6)
    }
    if !self.clickStatisticsURL.isEmpty {
      try visitor.visitSingularStringField(value: self.clickStatisticsURL, fieldNumber: 7)
    }
    if !self.floatingText.isEmpty {
      try visitor.visitSingularStringField(value: self.floatingText, fieldNumber: 8)
    }
    if !self.deeplink.isEmpty {
      try visitor.visitSingularStringField(value: self.deeplink, fieldNumber: 9)
    }
    if !self.scheme.isEmpty {
      try visitor.visitSingularStringField(value: self.scheme, fieldNumber: 10)
    }
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 11)
    }
    if !self.displayAdIcon.isEmpty {
      try visitor.visitSingularStringField(value: self.displayAdIcon, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Advertisement, rhs: Tieba_Advertisement) -> Bool {
    if lhs.time != rhs.time {return false}
    if lhs.pic != rhs.pic {return false}
    if lhs.picClick != rhs.picClick {return false}
    if lhs.jumpLink != rhs.jumpLink {return false}
    if lhs.advertisementID != rhs.advertisementID {return false}
    if lhs.viewStatisticsURL != rhs.viewStatisticsURL {return false}
    if lhs.clickStatisticsURL != rhs.clickStatisticsURL {return false}
    if lhs.floatingText != rhs.floatingText {return false}
    if lhs.deeplink != rhs.deeplink {return false}
    if lhs.scheme != rhs.scheme {return false}
    if lhs.packageName != rhs.packageName {return false}
    if lhs.displayAdIcon != rhs.displayAdIcon {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
