// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: AlaShareInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_AlaShareInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var content: String = String()

  var shareUserCount: Int32 = 0

  var shareCount: Int32 = 0

  var recordTid: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_AlaShareInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AlaShareInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}content\0\u{3}share_user_count\0\u{3}share_count\0\u{3}record_tid\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.shareUserCount) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.shareCount) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.recordTid) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 1)
    }
    if self.shareUserCount != 0 {
      try visitor.visitSingularInt32Field(value: self.shareUserCount, fieldNumber: 2)
    }
    if self.shareCount != 0 {
      try visitor.visitSingularInt32Field(value: self.shareCount, fieldNumber: 3)
    }
    if self.recordTid != 0 {
      try visitor.visitSingularInt64Field(value: self.recordTid, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_AlaShareInfo, rhs: Tieba_AlaShareInfo) -> Bool {
    if lhs.content != rhs.content {return false}
    if lhs.shareUserCount != rhs.shareUserCount {return false}
    if lhs.shareCount != rhs.shareCount {return false}
    if lhs.recordTid != rhs.recordTid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
