// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: AnchorInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_AnchorInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var portrait: String {
    get {_storage._portrait}
    set {_uniqueStorage()._portrait = newValue}
  }

  var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var startTime: Int32 {
    get {_storage._startTime}
    set {_uniqueStorage()._startTime = newValue}
  }

  var status: Int32 {
    get {_storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  var authorID: Int64 {
    get {_storage._authorID}
    set {_uniqueStorage()._authorID = newValue}
  }

  var authorName: String {
    get {_storage._authorName}
    set {_uniqueStorage()._authorName = newValue}
  }

  var listeners: Int32 {
    get {_storage._listeners}
    set {_uniqueStorage()._listeners = newValue}
  }

  var likers: Int32 {
    get {_storage._likers}
    set {_uniqueStorage()._likers = newValue}
  }

  var groupID: Int64 {
    get {_storage._groupID}
    set {_uniqueStorage()._groupID = newValue}
  }

  var intro: String {
    get {_storage._intro}
    set {_uniqueStorage()._intro = newValue}
  }

  var publisherPortrait: String {
    get {_storage._publisherPortrait}
    set {_uniqueStorage()._publisherPortrait = newValue}
  }

  var publisherName: String {
    get {_storage._publisherName}
    set {_uniqueStorage()._publisherName = newValue}
  }

  var publisherID: Int64 {
    get {_storage._publisherID}
    set {_uniqueStorage()._publisherID = newValue}
  }

  var forumName: String {
    get {_storage._forumName}
    set {_uniqueStorage()._forumName = newValue}
  }

  var fromType: Int32 {
    get {_storage._fromType}
    set {_uniqueStorage()._fromType = newValue}
  }

  var isVip: Int32 {
    get {_storage._isVip}
    set {_uniqueStorage()._isVip = newValue}
  }

  var labelID: Int32 {
    get {_storage._labelID}
    set {_uniqueStorage()._labelID = newValue}
  }

  var labelName: String {
    get {_storage._labelName}
    set {_uniqueStorage()._labelName = newValue}
  }

  var type: Int32 {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  var twzhiboInfo: Tieba_ZhiBoInfoTW {
    get {_storage._twzhiboInfo ?? Tieba_ZhiBoInfoTW()}
    set {_uniqueStorage()._twzhiboInfo = newValue}
  }
  /// Returns true if `twzhiboInfo` has been explicitly set.
  var hasTwzhiboInfo: Bool {_storage._twzhiboInfo != nil}
  /// Clears the value of `twzhiboInfo`. Subsequent reads from it will return its default value.
  mutating func clearTwzhiboInfo() {_uniqueStorage()._twzhiboInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_AnchorInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AnchorInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}portrait\0\u{1}name\0\u{3}start_time\0\u{1}status\0\u{3}author_id\0\u{3}author_name\0\u{1}listeners\0\u{1}likers\0\u{3}group_id\0\u{1}intro\0\u{1}publisherPortrait\0\u{1}publisherName\0\u{1}publisherId\0\u{1}forumName\0\u{3}from_type\0\u{3}is_vip\0\u{3}label_id\0\u{3}label_name\0\u{1}type\0\u{3}twzhibo_info\0")

  fileprivate class _StorageClass {
    var _portrait: String = String()
    var _name: String = String()
    var _startTime: Int32 = 0
    var _status: Int32 = 0
    var _authorID: Int64 = 0
    var _authorName: String = String()
    var _listeners: Int32 = 0
    var _likers: Int32 = 0
    var _groupID: Int64 = 0
    var _intro: String = String()
    var _publisherPortrait: String = String()
    var _publisherName: String = String()
    var _publisherID: Int64 = 0
    var _forumName: String = String()
    var _fromType: Int32 = 0
    var _isVip: Int32 = 0
    var _labelID: Int32 = 0
    var _labelName: String = String()
    var _type: Int32 = 0
    var _twzhiboInfo: Tieba_ZhiBoInfoTW? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _portrait = source._portrait
      _name = source._name
      _startTime = source._startTime
      _status = source._status
      _authorID = source._authorID
      _authorName = source._authorName
      _listeners = source._listeners
      _likers = source._likers
      _groupID = source._groupID
      _intro = source._intro
      _publisherPortrait = source._publisherPortrait
      _publisherName = source._publisherName
      _publisherID = source._publisherID
      _forumName = source._forumName
      _fromType = source._fromType
      _isVip = source._isVip
      _labelID = source._labelID
      _labelName = source._labelName
      _type = source._type
      _twzhiboInfo = source._twzhiboInfo
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._portrait) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularInt32Field(value: &_storage._startTime) }()
        case 4: try { try decoder.decodeSingularInt32Field(value: &_storage._status) }()
        case 5: try { try decoder.decodeSingularInt64Field(value: &_storage._authorID) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._authorName) }()
        case 7: try { try decoder.decodeSingularInt32Field(value: &_storage._listeners) }()
        case 8: try { try decoder.decodeSingularInt32Field(value: &_storage._likers) }()
        case 9: try { try decoder.decodeSingularInt64Field(value: &_storage._groupID) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._intro) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._publisherPortrait) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._publisherName) }()
        case 13: try { try decoder.decodeSingularInt64Field(value: &_storage._publisherID) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._forumName) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._fromType) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._isVip) }()
        case 17: try { try decoder.decodeSingularInt32Field(value: &_storage._labelID) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._labelName) }()
        case 19: try { try decoder.decodeSingularInt32Field(value: &_storage._type) }()
        case 20: try { try decoder.decodeSingularMessageField(value: &_storage._twzhiboInfo) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._portrait.isEmpty {
        try visitor.visitSingularStringField(value: _storage._portrait, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if _storage._startTime != 0 {
        try visitor.visitSingularInt32Field(value: _storage._startTime, fieldNumber: 3)
      }
      if _storage._status != 0 {
        try visitor.visitSingularInt32Field(value: _storage._status, fieldNumber: 4)
      }
      if _storage._authorID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._authorID, fieldNumber: 5)
      }
      if !_storage._authorName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._authorName, fieldNumber: 6)
      }
      if _storage._listeners != 0 {
        try visitor.visitSingularInt32Field(value: _storage._listeners, fieldNumber: 7)
      }
      if _storage._likers != 0 {
        try visitor.visitSingularInt32Field(value: _storage._likers, fieldNumber: 8)
      }
      if _storage._groupID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._groupID, fieldNumber: 9)
      }
      if !_storage._intro.isEmpty {
        try visitor.visitSingularStringField(value: _storage._intro, fieldNumber: 10)
      }
      if !_storage._publisherPortrait.isEmpty {
        try visitor.visitSingularStringField(value: _storage._publisherPortrait, fieldNumber: 11)
      }
      if !_storage._publisherName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._publisherName, fieldNumber: 12)
      }
      if _storage._publisherID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._publisherID, fieldNumber: 13)
      }
      if !_storage._forumName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._forumName, fieldNumber: 14)
      }
      if _storage._fromType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._fromType, fieldNumber: 15)
      }
      if _storage._isVip != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isVip, fieldNumber: 16)
      }
      if _storage._labelID != 0 {
        try visitor.visitSingularInt32Field(value: _storage._labelID, fieldNumber: 17)
      }
      if !_storage._labelName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._labelName, fieldNumber: 18)
      }
      if _storage._type != 0 {
        try visitor.visitSingularInt32Field(value: _storage._type, fieldNumber: 19)
      }
      try { if let v = _storage._twzhiboInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_AnchorInfo, rhs: Tieba_AnchorInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._portrait != rhs_storage._portrait {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._startTime != rhs_storage._startTime {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._authorID != rhs_storage._authorID {return false}
        if _storage._authorName != rhs_storage._authorName {return false}
        if _storage._listeners != rhs_storage._listeners {return false}
        if _storage._likers != rhs_storage._likers {return false}
        if _storage._groupID != rhs_storage._groupID {return false}
        if _storage._intro != rhs_storage._intro {return false}
        if _storage._publisherPortrait != rhs_storage._publisherPortrait {return false}
        if _storage._publisherName != rhs_storage._publisherName {return false}
        if _storage._publisherID != rhs_storage._publisherID {return false}
        if _storage._forumName != rhs_storage._forumName {return false}
        if _storage._fromType != rhs_storage._fromType {return false}
        if _storage._isVip != rhs_storage._isVip {return false}
        if _storage._labelID != rhs_storage._labelID {return false}
        if _storage._labelName != rhs_storage._labelName {return false}
        if _storage._type != rhs_storage._type {return false}
        if _storage._twzhiboInfo != rhs_storage._twzhiboInfo {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
