// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: App.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_App: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Int32 {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  var pos: Int32 {
    get {_storage._pos}
    set {_uniqueStorage()._pos = newValue}
  }

  var iconURL: String {
    get {_storage._iconURL}
    set {_uniqueStorage()._iconURL = newValue}
  }

  var iconLink: String {
    get {_storage._iconLink}
    set {_uniqueStorage()._iconLink = newValue}
  }

  var appName: String {
    get {_storage._appName}
    set {_uniqueStorage()._appName = newValue}
  }

  var appDesc: String {
    get {_storage._appDesc}
    set {_uniqueStorage()._appDesc = newValue}
  }

  var pName: String {
    get {_storage._pName}
    set {_uniqueStorage()._pName = newValue}
  }

  var pURL: String {
    get {_storage._pURL}
    set {_uniqueStorage()._pURL = newValue}
  }

  var imgURL: String {
    get {_storage._imgURL}
    set {_uniqueStorage()._imgURL = newValue}
  }

  var appTime: Int32 {
    get {_storage._appTime}
    set {_uniqueStorage()._appTime = newValue}
  }

  var webURL: String {
    get {_storage._webURL}
    set {_uniqueStorage()._webURL = newValue}
  }

  var adID: String {
    get {_storage._adID}
    set {_uniqueStorage()._adID = newValue}
  }

  var id: String {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var urlType: Int32 {
    get {_storage._urlType}
    set {_uniqueStorage()._urlType = newValue}
  }

  var url: String {
    get {_storage._url}
    set {_uniqueStorage()._url = newValue}
  }

  var iosURL: String {
    get {_storage._iosURL}
    set {_uniqueStorage()._iosURL = newValue}
  }

  var apkURL: String {
    get {_storage._apkURL}
    set {_uniqueStorage()._apkURL = newValue}
  }

  var apkName: String {
    get {_storage._apkName}
    set {_uniqueStorage()._apkName = newValue}
  }

  var posName: String {
    get {_storage._posName}
    set {_uniqueStorage()._posName = newValue}
  }

  var firstName: String {
    get {_storage._firstName}
    set {_uniqueStorage()._firstName = newValue}
  }

  var secondName: String {
    get {_storage._secondName}
    set {_uniqueStorage()._secondName = newValue}
  }

  var cpid: Int32 {
    get {_storage._cpid}
    set {_uniqueStorage()._cpid = newValue}
  }

  var abtest: String {
    get {_storage._abtest}
    set {_uniqueStorage()._abtest = newValue}
  }

  var planID: Int32 {
    get {_storage._planID}
    set {_uniqueStorage()._planID = newValue}
  }

  var userID: String {
    get {_storage._userID}
    set {_uniqueStorage()._userID = newValue}
  }

  var price: String {
    get {_storage._price}
    set {_uniqueStorage()._price = newValue}
  }

  var verify: String {
    get {_storage._verify}
    set {_uniqueStorage()._verify = newValue}
  }

  var extInfo: String {
    get {_storage._extInfo}
    set {_uniqueStorage()._extInfo = newValue}
  }

  var goodsInfo: [Tieba_GoodsInfo] {
    get {_storage._goodsInfo}
    set {_uniqueStorage()._goodsInfo = newValue}
  }

  var locCode: String {
    get {_storage._locCode}
    set {_uniqueStorage()._locCode = newValue}
  }

  var deepURL: String {
    get {_storage._deepURL}
    set {_uniqueStorage()._deepURL = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_App: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".App"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}pos\0\u{3}icon_url\0\u{3}icon_link\0\u{3}app_name\0\u{3}app_desc\0\u{3}p_name\0\u{3}p_url\0\u{3}img_url\0\u{3}app_time\0\u{3}web_url\0\u{3}ad_id\0\u{1}id\0\u{1}name\0\u{3}url_type\0\u{1}url\0\u{3}ios_url\0\u{3}apk_url\0\u{3}apk_name\0\u{3}pos_name\0\u{3}first_name\0\u{3}second_name\0\u{1}cpid\0\u{1}abtest\0\u{3}plan_id\0\u{3}user_id\0\u{1}price\0\u{1}verify\0\u{3}ext_info\0\u{3}goods_info\0\u{3}loc_code\0\u{3}deep_url\0")

  fileprivate class _StorageClass {
    var _type: Int32 = 0
    var _pos: Int32 = 0
    var _iconURL: String = String()
    var _iconLink: String = String()
    var _appName: String = String()
    var _appDesc: String = String()
    var _pName: String = String()
    var _pURL: String = String()
    var _imgURL: String = String()
    var _appTime: Int32 = 0
    var _webURL: String = String()
    var _adID: String = String()
    var _id: String = String()
    var _name: String = String()
    var _urlType: Int32 = 0
    var _url: String = String()
    var _iosURL: String = String()
    var _apkURL: String = String()
    var _apkName: String = String()
    var _posName: String = String()
    var _firstName: String = String()
    var _secondName: String = String()
    var _cpid: Int32 = 0
    var _abtest: String = String()
    var _planID: Int32 = 0
    var _userID: String = String()
    var _price: String = String()
    var _verify: String = String()
    var _extInfo: String = String()
    var _goodsInfo: [Tieba_GoodsInfo] = []
    var _locCode: String = String()
    var _deepURL: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _type = source._type
      _pos = source._pos
      _iconURL = source._iconURL
      _iconLink = source._iconLink
      _appName = source._appName
      _appDesc = source._appDesc
      _pName = source._pName
      _pURL = source._pURL
      _imgURL = source._imgURL
      _appTime = source._appTime
      _webURL = source._webURL
      _adID = source._adID
      _id = source._id
      _name = source._name
      _urlType = source._urlType
      _url = source._url
      _iosURL = source._iosURL
      _apkURL = source._apkURL
      _apkName = source._apkName
      _posName = source._posName
      _firstName = source._firstName
      _secondName = source._secondName
      _cpid = source._cpid
      _abtest = source._abtest
      _planID = source._planID
      _userID = source._userID
      _price = source._price
      _verify = source._verify
      _extInfo = source._extInfo
      _goodsInfo = source._goodsInfo
      _locCode = source._locCode
      _deepURL = source._deepURL
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._type) }()
        case 2: try { try decoder.decodeSingularInt32Field(value: &_storage._pos) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._iconURL) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._iconLink) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._appName) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._appDesc) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._pName) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._pURL) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._imgURL) }()
        case 10: try { try decoder.decodeSingularInt32Field(value: &_storage._appTime) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._webURL) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._adID) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._urlType) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._url) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._iosURL) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._apkURL) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._apkName) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._posName) }()
        case 21: try { try decoder.decodeSingularStringField(value: &_storage._firstName) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._secondName) }()
        case 23: try { try decoder.decodeSingularInt32Field(value: &_storage._cpid) }()
        case 24: try { try decoder.decodeSingularStringField(value: &_storage._abtest) }()
        case 25: try { try decoder.decodeSingularInt32Field(value: &_storage._planID) }()
        case 26: try { try decoder.decodeSingularStringField(value: &_storage._userID) }()
        case 27: try { try decoder.decodeSingularStringField(value: &_storage._price) }()
        case 28: try { try decoder.decodeSingularStringField(value: &_storage._verify) }()
        case 29: try { try decoder.decodeSingularStringField(value: &_storage._extInfo) }()
        case 30: try { try decoder.decodeRepeatedMessageField(value: &_storage._goodsInfo) }()
        case 31: try { try decoder.decodeSingularStringField(value: &_storage._locCode) }()
        case 32: try { try decoder.decodeSingularStringField(value: &_storage._deepURL) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._type != 0 {
        try visitor.visitSingularInt32Field(value: _storage._type, fieldNumber: 1)
      }
      if _storage._pos != 0 {
        try visitor.visitSingularInt32Field(value: _storage._pos, fieldNumber: 2)
      }
      if !_storage._iconURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._iconURL, fieldNumber: 3)
      }
      if !_storage._iconLink.isEmpty {
        try visitor.visitSingularStringField(value: _storage._iconLink, fieldNumber: 4)
      }
      if !_storage._appName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._appName, fieldNumber: 5)
      }
      if !_storage._appDesc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._appDesc, fieldNumber: 6)
      }
      if !_storage._pName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._pName, fieldNumber: 7)
      }
      if !_storage._pURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._pURL, fieldNumber: 8)
      }
      if !_storage._imgURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._imgURL, fieldNumber: 9)
      }
      if _storage._appTime != 0 {
        try visitor.visitSingularInt32Field(value: _storage._appTime, fieldNumber: 10)
      }
      if !_storage._webURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._webURL, fieldNumber: 11)
      }
      if !_storage._adID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._adID, fieldNumber: 12)
      }
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 13)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 14)
      }
      if _storage._urlType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._urlType, fieldNumber: 15)
      }
      if !_storage._url.isEmpty {
        try visitor.visitSingularStringField(value: _storage._url, fieldNumber: 16)
      }
      if !_storage._iosURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._iosURL, fieldNumber: 17)
      }
      if !_storage._apkURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._apkURL, fieldNumber: 18)
      }
      if !_storage._apkName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._apkName, fieldNumber: 19)
      }
      if !_storage._posName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._posName, fieldNumber: 20)
      }
      if !_storage._firstName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._firstName, fieldNumber: 21)
      }
      if !_storage._secondName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._secondName, fieldNumber: 22)
      }
      if _storage._cpid != 0 {
        try visitor.visitSingularInt32Field(value: _storage._cpid, fieldNumber: 23)
      }
      if !_storage._abtest.isEmpty {
        try visitor.visitSingularStringField(value: _storage._abtest, fieldNumber: 24)
      }
      if _storage._planID != 0 {
        try visitor.visitSingularInt32Field(value: _storage._planID, fieldNumber: 25)
      }
      if !_storage._userID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._userID, fieldNumber: 26)
      }
      if !_storage._price.isEmpty {
        try visitor.visitSingularStringField(value: _storage._price, fieldNumber: 27)
      }
      if !_storage._verify.isEmpty {
        try visitor.visitSingularStringField(value: _storage._verify, fieldNumber: 28)
      }
      if !_storage._extInfo.isEmpty {
        try visitor.visitSingularStringField(value: _storage._extInfo, fieldNumber: 29)
      }
      if !_storage._goodsInfo.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._goodsInfo, fieldNumber: 30)
      }
      if !_storage._locCode.isEmpty {
        try visitor.visitSingularStringField(value: _storage._locCode, fieldNumber: 31)
      }
      if !_storage._deepURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._deepURL, fieldNumber: 32)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_App, rhs: Tieba_App) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._type != rhs_storage._type {return false}
        if _storage._pos != rhs_storage._pos {return false}
        if _storage._iconURL != rhs_storage._iconURL {return false}
        if _storage._iconLink != rhs_storage._iconLink {return false}
        if _storage._appName != rhs_storage._appName {return false}
        if _storage._appDesc != rhs_storage._appDesc {return false}
        if _storage._pName != rhs_storage._pName {return false}
        if _storage._pURL != rhs_storage._pURL {return false}
        if _storage._imgURL != rhs_storage._imgURL {return false}
        if _storage._appTime != rhs_storage._appTime {return false}
        if _storage._webURL != rhs_storage._webURL {return false}
        if _storage._adID != rhs_storage._adID {return false}
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._urlType != rhs_storage._urlType {return false}
        if _storage._url != rhs_storage._url {return false}
        if _storage._iosURL != rhs_storage._iosURL {return false}
        if _storage._apkURL != rhs_storage._apkURL {return false}
        if _storage._apkName != rhs_storage._apkName {return false}
        if _storage._posName != rhs_storage._posName {return false}
        if _storage._firstName != rhs_storage._firstName {return false}
        if _storage._secondName != rhs_storage._secondName {return false}
        if _storage._cpid != rhs_storage._cpid {return false}
        if _storage._abtest != rhs_storage._abtest {return false}
        if _storage._planID != rhs_storage._planID {return false}
        if _storage._userID != rhs_storage._userID {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._verify != rhs_storage._verify {return false}
        if _storage._extInfo != rhs_storage._extInfo {return false}
        if _storage._goodsInfo != rhs_storage._goodsInfo {return false}
        if _storage._locCode != rhs_storage._locCode {return false}
        if _storage._deepURL != rhs_storage._deepURL {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
