// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: BaijiahaoInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_BaijiahaoInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var avatar: String = String()

  var avatarH: String = String()

  var brief: String = String()

  var authID: Int32 = 0

  var authDesc: String = String()

  var canModifyAvatar: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_BaijiahaoInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BaijiahaoInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}avatar\0\u{3}avatar_h\0\u{1}brief\0\u{3}auth_id\0\u{3}auth_desc\0\u{3}can_modify_avatar\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.avatar) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.avatarH) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.brief) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.authID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.authDesc) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.canModifyAvatar) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.avatar.isEmpty {
      try visitor.visitSingularStringField(value: self.avatar, fieldNumber: 2)
    }
    if !self.avatarH.isEmpty {
      try visitor.visitSingularStringField(value: self.avatarH, fieldNumber: 3)
    }
    if !self.brief.isEmpty {
      try visitor.visitSingularStringField(value: self.brief, fieldNumber: 4)
    }
    if self.authID != 0 {
      try visitor.visitSingularInt32Field(value: self.authID, fieldNumber: 5)
    }
    if !self.authDesc.isEmpty {
      try visitor.visitSingularStringField(value: self.authDesc, fieldNumber: 6)
    }
    if self.canModifyAvatar != 0 {
      try visitor.visitSingularInt32Field(value: self.canModifyAvatar, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_BaijiahaoInfo, rhs: Tieba_BaijiahaoInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.avatar != rhs.avatar {return false}
    if lhs.avatarH != rhs.avatarH {return false}
    if lhs.brief != rhs.brief {return false}
    if lhs.authID != rhs.authID {return false}
    if lhs.authDesc != rhs.authDesc {return false}
    if lhs.canModifyAvatar != rhs.canModifyAvatar {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
