// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: BawuThrones.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_BawuThrones: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var totalRecommendNum: Int32 = 0

  var usedRecommendNum: Int32 = 0

  var bazhuLevel: String = String()

  var usedBcastCnt: Int32 = 0

  var totalBcastCnt: Int32 = 0

  var newestBcastPv: Int32 = 0

  var hasSendBcast_p: Int32 = 0

  var newestBcastPushuserCnt: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_BawuThrones: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BawuThrones"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}total_recommend_num\0\u{3}used_recommend_num\0\u{3}bazhu_level\0\u{3}used_bcast_cnt\0\u{3}total_bcast_cnt\0\u{3}newest_bcast_pv\0\u{3}has_send_bcast\0\u{3}newest_bcast_pushuser_cnt\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.totalRecommendNum) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.usedRecommendNum) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.bazhuLevel) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.usedBcastCnt) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.totalBcastCnt) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.newestBcastPv) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.hasSendBcast_p) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.newestBcastPushuserCnt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.totalRecommendNum != 0 {
      try visitor.visitSingularInt32Field(value: self.totalRecommendNum, fieldNumber: 1)
    }
    if self.usedRecommendNum != 0 {
      try visitor.visitSingularInt32Field(value: self.usedRecommendNum, fieldNumber: 2)
    }
    if !self.bazhuLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.bazhuLevel, fieldNumber: 3)
    }
    if self.usedBcastCnt != 0 {
      try visitor.visitSingularInt32Field(value: self.usedBcastCnt, fieldNumber: 4)
    }
    if self.totalBcastCnt != 0 {
      try visitor.visitSingularInt32Field(value: self.totalBcastCnt, fieldNumber: 5)
    }
    if self.newestBcastPv != 0 {
      try visitor.visitSingularInt32Field(value: self.newestBcastPv, fieldNumber: 6)
    }
    if self.hasSendBcast_p != 0 {
      try visitor.visitSingularInt32Field(value: self.hasSendBcast_p, fieldNumber: 7)
    }
    if self.newestBcastPushuserCnt != 0 {
      try visitor.visitSingularInt32Field(value: self.newestBcastPushuserCnt, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_BawuThrones, rhs: Tieba_BawuThrones) -> Bool {
    if lhs.totalRecommendNum != rhs.totalRecommendNum {return false}
    if lhs.usedRecommendNum != rhs.usedRecommendNum {return false}
    if lhs.bazhuLevel != rhs.bazhuLevel {return false}
    if lhs.usedBcastCnt != rhs.usedBcastCnt {return false}
    if lhs.totalBcastCnt != rhs.totalBcastCnt {return false}
    if lhs.newestBcastPv != rhs.newestBcastPv {return false}
    if lhs.hasSendBcast_p != rhs.hasSendBcast_p {return false}
    if lhs.newestBcastPushuserCnt != rhs.newestBcastPushuserCnt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
