// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: BawuRoleInfoPub.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_BawuRoleInfoPub: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var forumID: UInt64 = 0

  var userID: Int64 = 0

  var roleID: Int32 = 0

  var roleName: String = String()

  var portrait: String = String()

  var userLevel: Int32 = 0

  var levelName: String = String()

  var userName: String = String()

  var nameShow: String = String()

  var baijiahaoInfo: Tieba_BaijiahaoInfo {
    get {_baijiahaoInfo ?? Tieba_BaijiahaoInfo()}
    set {_baijiahaoInfo = newValue}
  }
  /// Returns true if `baijiahaoInfo` has been explicitly set.
  var hasBaijiahaoInfo: Bool {self._baijiahaoInfo != nil}
  /// Clears the value of `baijiahaoInfo`. Subsequent reads from it will return its default value.
  mutating func clearBaijiahaoInfo() {self._baijiahaoInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _baijiahaoInfo: Tieba_BaijiahaoInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_BawuRoleInfoPub: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BawuRoleInfoPub"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}forum_id\0\u{3}user_id\0\u{3}role_id\0\u{3}role_name\0\u{1}portrait\0\u{3}user_level\0\u{3}level_name\0\u{3}user_name\0\u{3}name_show\0\u{3}baijiahao_info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.forumID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.userID) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.roleID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.roleName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.portrait) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.userLevel) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.levelName) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.userName) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.nameShow) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._baijiahaoInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.forumID != 0 {
      try visitor.visitSingularUInt64Field(value: self.forumID, fieldNumber: 1)
    }
    if self.userID != 0 {
      try visitor.visitSingularInt64Field(value: self.userID, fieldNumber: 2)
    }
    if self.roleID != 0 {
      try visitor.visitSingularInt32Field(value: self.roleID, fieldNumber: 3)
    }
    if !self.roleName.isEmpty {
      try visitor.visitSingularStringField(value: self.roleName, fieldNumber: 4)
    }
    if !self.portrait.isEmpty {
      try visitor.visitSingularStringField(value: self.portrait, fieldNumber: 5)
    }
    if self.userLevel != 0 {
      try visitor.visitSingularInt32Field(value: self.userLevel, fieldNumber: 6)
    }
    if !self.levelName.isEmpty {
      try visitor.visitSingularStringField(value: self.levelName, fieldNumber: 7)
    }
    if !self.userName.isEmpty {
      try visitor.visitSingularStringField(value: self.userName, fieldNumber: 8)
    }
    if !self.nameShow.isEmpty {
      try visitor.visitSingularStringField(value: self.nameShow, fieldNumber: 9)
    }
    try { if let v = self._baijiahaoInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_BawuRoleInfoPub, rhs: Tieba_BawuRoleInfoPub) -> Bool {
    if lhs.forumID != rhs.forumID {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.roleID != rhs.roleID {return false}
    if lhs.roleName != rhs.roleName {return false}
    if lhs.portrait != rhs.portrait {return false}
    if lhs.userLevel != rhs.userLevel {return false}
    if lhs.levelName != rhs.levelName {return false}
    if lhs.userName != rhs.userName {return false}
    if lhs.nameShow != rhs.nameShow {return false}
    if lhs._baijiahaoInfo != rhs._baijiahaoInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
