// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ForumDynamic.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_ForumDynamic: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var forumID: Int64 = 0

  var forumName: String = String()

  var avatar: String = String()

  var slogan: String = String()

  var isLike: UInt32 = 0

  var memberCount: UInt32 = 0

  var threadCount: UInt32 = 0

  var userThreadCount: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_ForumDynamic: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ForumDynamic"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}forum_id\0\u{3}forum_name\0\u{1}avatar\0\u{1}slogan\0\u{3}is_like\0\u{3}member_count\0\u{3}thread_count\0\u{4}\u{2}user_thread_count\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.forumID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.forumName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.avatar) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.slogan) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.isLike) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.memberCount) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.threadCount) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.userThreadCount) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.forumID != 0 {
      try visitor.visitSingularInt64Field(value: self.forumID, fieldNumber: 1)
    }
    if !self.forumName.isEmpty {
      try visitor.visitSingularStringField(value: self.forumName, fieldNumber: 2)
    }
    if !self.avatar.isEmpty {
      try visitor.visitSingularStringField(value: self.avatar, fieldNumber: 3)
    }
    if !self.slogan.isEmpty {
      try visitor.visitSingularStringField(value: self.slogan, fieldNumber: 4)
    }
    if self.isLike != 0 {
      try visitor.visitSingularUInt32Field(value: self.isLike, fieldNumber: 5)
    }
    if self.memberCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.memberCount, fieldNumber: 6)
    }
    if self.threadCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.threadCount, fieldNumber: 7)
    }
    if self.userThreadCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.userThreadCount, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_ForumDynamic, rhs: Tieba_ForumDynamic) -> Bool {
    if lhs.forumID != rhs.forumID {return false}
    if lhs.forumName != rhs.forumName {return false}
    if lhs.avatar != rhs.avatar {return false}
    if lhs.slogan != rhs.slogan {return false}
    if lhs.isLike != rhs.isLike {return false}
    if lhs.memberCount != rhs.memberCount {return false}
    if lhs.threadCount != rhs.threadCount {return false}
    if lhs.userThreadCount != rhs.userThreadCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
