// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ForumRuleDetail/ForumRuleDetailResponseData.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_ForumRuleDetail_ForumRuleDetailResponseData: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var forum: Tieba_ForumInfo {
    get {_storage._forum ?? Tieba_ForumInfo()}
    set {_uniqueStorage()._forum = newValue}
  }
  /// Returns true if `forum` has been explicitly set.
  var hasForum: Bool {_storage._forum != nil}
  /// Clears the value of `forum`. Subsequent reads from it will return its default value.
  mutating func clearForum() {_uniqueStorage()._forum = nil}

  var title: String {
    get {_storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  var preface: String {
    get {_storage._preface}
    set {_uniqueStorage()._preface = newValue}
  }

  var rules: [Tieba_ForumRule] {
    get {_storage._rules}
    set {_uniqueStorage()._rules = newValue}
  }

  var auditStatus: Int32 {
    get {_storage._auditStatus}
    set {_uniqueStorage()._auditStatus = newValue}
  }

  var auditOpinion: String {
    get {_storage._auditOpinion}
    set {_uniqueStorage()._auditOpinion = newValue}
  }

  var isManager: Int32 {
    get {_storage._isManager}
    set {_uniqueStorage()._isManager = newValue}
  }

  var forumRuleID: Int64 {
    get {_storage._forumRuleID}
    set {_uniqueStorage()._forumRuleID = newValue}
  }

  var publishTime: String {
    get {_storage._publishTime}
    set {_uniqueStorage()._publishTime = newValue}
  }

  var bazhu: Tieba_BawuRoleInfoPub {
    get {_storage._bazhu ?? Tieba_BawuRoleInfoPub()}
    set {_uniqueStorage()._bazhu = newValue}
  }
  /// Returns true if `bazhu` has been explicitly set.
  var hasBazhu: Bool {_storage._bazhu != nil}
  /// Clears the value of `bazhu`. Subsequent reads from it will return its default value.
  mutating func clearBazhu() {_uniqueStorage()._bazhu = nil}

  var curTime: String {
    get {_storage._curTime}
    set {_uniqueStorage()._curTime = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.forumRuleDetail"

nonisolated extension Tieba_ForumRuleDetail_ForumRuleDetailResponseData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ForumRuleDetailResponseData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}forum\0\u{1}title\0\u{1}preface\0\u{1}rules\0\u{3}audit_status\0\u{3}audit_opinion\0\u{3}is_manager\0\u{3}forum_rule_id\0\u{3}publish_time\0\u{1}bazhu\0\u{3}cur_time\0")

  fileprivate class _StorageClass {
    var _forum: Tieba_ForumInfo? = nil
    var _title: String = String()
    var _preface: String = String()
    var _rules: [Tieba_ForumRule] = []
    var _auditStatus: Int32 = 0
    var _auditOpinion: String = String()
    var _isManager: Int32 = 0
    var _forumRuleID: Int64 = 0
    var _publishTime: String = String()
    var _bazhu: Tieba_BawuRoleInfoPub? = nil
    var _curTime: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _forum = source._forum
      _title = source._title
      _preface = source._preface
      _rules = source._rules
      _auditStatus = source._auditStatus
      _auditOpinion = source._auditOpinion
      _isManager = source._isManager
      _forumRuleID = source._forumRuleID
      _publishTime = source._publishTime
      _bazhu = source._bazhu
      _curTime = source._curTime
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._forum) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._preface) }()
        case 5: try { try decoder.decodeRepeatedMessageField(value: &_storage._rules) }()
        case 6: try { try decoder.decodeSingularInt32Field(value: &_storage._auditStatus) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._auditOpinion) }()
        case 8: try { try decoder.decodeSingularInt32Field(value: &_storage._isManager) }()
        case 9: try { try decoder.decodeSingularInt64Field(value: &_storage._forumRuleID) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._publishTime) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._bazhu) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._curTime) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._forum {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 3)
      }
      if !_storage._preface.isEmpty {
        try visitor.visitSingularStringField(value: _storage._preface, fieldNumber: 4)
      }
      if !_storage._rules.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._rules, fieldNumber: 5)
      }
      if _storage._auditStatus != 0 {
        try visitor.visitSingularInt32Field(value: _storage._auditStatus, fieldNumber: 6)
      }
      if !_storage._auditOpinion.isEmpty {
        try visitor.visitSingularStringField(value: _storage._auditOpinion, fieldNumber: 7)
      }
      if _storage._isManager != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isManager, fieldNumber: 8)
      }
      if _storage._forumRuleID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._forumRuleID, fieldNumber: 9)
      }
      if !_storage._publishTime.isEmpty {
        try visitor.visitSingularStringField(value: _storage._publishTime, fieldNumber: 10)
      }
      try { if let v = _storage._bazhu {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      if !_storage._curTime.isEmpty {
        try visitor.visitSingularStringField(value: _storage._curTime, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_ForumRuleDetail_ForumRuleDetailResponseData, rhs: Tieba_ForumRuleDetail_ForumRuleDetailResponseData) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._forum != rhs_storage._forum {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._preface != rhs_storage._preface {return false}
        if _storage._rules != rhs_storage._rules {return false}
        if _storage._auditStatus != rhs_storage._auditStatus {return false}
        if _storage._auditOpinion != rhs_storage._auditOpinion {return false}
        if _storage._isManager != rhs_storage._isManager {return false}
        if _storage._forumRuleID != rhs_storage._forumRuleID {return false}
        if _storage._publishTime != rhs_storage._publishTime {return false}
        if _storage._bazhu != rhs_storage._bazhu {return false}
        if _storage._curTime != rhs_storage._curTime {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
