// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: FrsPage/RankInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_FrsPage_RankInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var signCount: Int32 = 0

  var signRank: Int32 = 0

  var memberCount: Int32 = 0

  var dirRate: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.frsPage"

nonisolated extension Tieba_FrsPage_RankInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RankInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sign_count\0\u{3}sign_rank\0\u{3}member_count\0\u{3}dir_rate\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.signCount) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.signRank) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.memberCount) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.dirRate) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.signCount != 0 {
      try visitor.visitSingularInt32Field(value: self.signCount, fieldNumber: 1)
    }
    if self.signRank != 0 {
      try visitor.visitSingularInt32Field(value: self.signRank, fieldNumber: 2)
    }
    if self.memberCount != 0 {
      try visitor.visitSingularInt32Field(value: self.memberCount, fieldNumber: 3)
    }
    if self.dirRate.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.dirRate, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_FrsPage_RankInfo, rhs: Tieba_FrsPage_RankInfo) -> Bool {
    if lhs.signCount != rhs.signCount {return false}
    if lhs.signRank != rhs.signRank {return false}
    if lhs.memberCount != rhs.memberCount {return false}
    if lhs.dirRate != rhs.dirRate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
