// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: FrsPage/NavTabInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_FrsPage_NavTabInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var tab: [Tieba_FrsTabInfo] = []

  var menu: [Tieba_FrsTabInfo] = []

  var head: [Tieba_FrsTabInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.frsPage"

nonisolated extension Tieba_FrsPage_NavTabInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NavTabInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}tab\0\u{1}menu\0\u{1}head\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.tab) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.menu) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.head) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.tab.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tab, fieldNumber: 1)
    }
    if !self.menu.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.menu, fieldNumber: 2)
    }
    if !self.head.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.head, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_FrsPage_NavTabInfo, rhs: Tieba_FrsPage_NavTabInfo) -> Bool {
    if lhs.tab != rhs.tab {return false}
    if lhs.menu != rhs.menu {return false}
    if lhs.head != rhs.head {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
