// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: FrsPage/SignForum.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_FrsPage_SignForum: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var isOn: Int32 = 0

  var isFilter: Int32 = 0

  var forumInfo: Tieba_FrsPage_Forum {
    get {_forumInfo ?? Tieba_FrsPage_Forum()}
    set {_forumInfo = newValue}
  }
  /// Returns true if `forumInfo` has been explicitly set.
  var hasForumInfo: Bool {self._forumInfo != nil}
  /// Clears the value of `forumInfo`. Subsequent reads from it will return its default value.
  mutating func clearForumInfo() {self._forumInfo = nil}

  var currentRankInfo: Tieba_FrsPage_RankInfo {
    get {_currentRankInfo ?? Tieba_FrsPage_RankInfo()}
    set {_currentRankInfo = newValue}
  }
  /// Returns true if `currentRankInfo` has been explicitly set.
  var hasCurrentRankInfo: Bool {self._currentRankInfo != nil}
  /// Clears the value of `currentRankInfo`. Subsequent reads from it will return its default value.
  mutating func clearCurrentRankInfo() {self._currentRankInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _forumInfo: Tieba_FrsPage_Forum? = nil
  fileprivate var _currentRankInfo: Tieba_FrsPage_RankInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.frsPage"

nonisolated extension Tieba_FrsPage_SignForum: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SignForum"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_on\0\u{3}is_filter\0\u{3}forum_info\0\u{3}current_rank_info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.isOn) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.isFilter) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._forumInfo) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._currentRankInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.isOn != 0 {
      try visitor.visitSingularInt32Field(value: self.isOn, fieldNumber: 1)
    }
    if self.isFilter != 0 {
      try visitor.visitSingularInt32Field(value: self.isFilter, fieldNumber: 2)
    }
    try { if let v = self._forumInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._currentRankInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_FrsPage_SignForum, rhs: Tieba_FrsPage_SignForum) -> Bool {
    if lhs.isOn != rhs.isOn {return false}
    if lhs.isFilter != rhs.isFilter {return false}
    if lhs._forumInfo != rhs._forumInfo {return false}
    if lhs._currentRankInfo != rhs._currentRankInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
