// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: FrsPage/SignUser.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_FrsPage_SignUser: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userID: Int64 = 0

  var isSignIn: Int32 = 0

  var userSignRank: Int32 = 0

  var signTime: Int32 = 0

  var contSignNum: Int32 = 0

  var coutTotalSignNum: Int32 = 0

  var isOrgDisabled: Int32 = 0

  var cSignNum: Int32 = 0

  var hunSignNum: Int32 = 0

  var totalResignNum: Int32 = 0

  var missSignNum: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.frsPage"

nonisolated extension Tieba_FrsPage_SignUser: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SignUser"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0\u{3}is_sign_in\0\u{3}user_sign_rank\0\u{3}sign_time\0\u{3}cont_sign_num\0\u{3}cout_total_sign_num\0\u{3}is_org_disabled\0\u{3}c_sign_num\0\u{3}hun_sign_num\0\u{3}total_resign_num\0\u{3}miss_sign_num\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.userID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.isSignIn) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.userSignRank) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.signTime) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.contSignNum) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.coutTotalSignNum) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.isOrgDisabled) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.cSignNum) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.hunSignNum) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.totalResignNum) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self.missSignNum) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.userID != 0 {
      try visitor.visitSingularInt64Field(value: self.userID, fieldNumber: 1)
    }
    if self.isSignIn != 0 {
      try visitor.visitSingularInt32Field(value: self.isSignIn, fieldNumber: 2)
    }
    if self.userSignRank != 0 {
      try visitor.visitSingularInt32Field(value: self.userSignRank, fieldNumber: 3)
    }
    if self.signTime != 0 {
      try visitor.visitSingularInt32Field(value: self.signTime, fieldNumber: 4)
    }
    if self.contSignNum != 0 {
      try visitor.visitSingularInt32Field(value: self.contSignNum, fieldNumber: 5)
    }
    if self.coutTotalSignNum != 0 {
      try visitor.visitSingularInt32Field(value: self.coutTotalSignNum, fieldNumber: 6)
    }
    if self.isOrgDisabled != 0 {
      try visitor.visitSingularInt32Field(value: self.isOrgDisabled, fieldNumber: 7)
    }
    if self.cSignNum != 0 {
      try visitor.visitSingularInt32Field(value: self.cSignNum, fieldNumber: 8)
    }
    if self.hunSignNum != 0 {
      try visitor.visitSingularInt32Field(value: self.hunSignNum, fieldNumber: 9)
    }
    if self.totalResignNum != 0 {
      try visitor.visitSingularInt32Field(value: self.totalResignNum, fieldNumber: 10)
    }
    if self.missSignNum != 0 {
      try visitor.visitSingularInt32Field(value: self.missSignNum, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_FrsPage_SignUser, rhs: Tieba_FrsPage_SignUser) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.isSignIn != rhs.isSignIn {return false}
    if lhs.userSignRank != rhs.userSignRank {return false}
    if lhs.signTime != rhs.signTime {return false}
    if lhs.contSignNum != rhs.contSignNum {return false}
    if lhs.coutTotalSignNum != rhs.coutTotalSignNum {return false}
    if lhs.isOrgDisabled != rhs.isOrgDisabled {return false}
    if lhs.cSignNum != rhs.cSignNum {return false}
    if lhs.hunSignNum != rhs.hunSignNum {return false}
    if lhs.totalResignNum != rhs.totalResignNum {return false}
    if lhs.missSignNum != rhs.missSignNum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
