// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: GetForumDetail/UniversityInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_GetForumDetail_UniversityInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var title: String = String()

  var picURL: String = String()

  var toURL: String = String()

  var type: Int32 = 0

  var agreeNum: Int64 = 0

  var browseNum: Int64 = 0

  var videoTime: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.getForumDetail"

nonisolated extension Tieba_GetForumDetail_UniversityInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UniversityInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{3}pic_url\0\u{3}to_url\0\u{1}type\0\u{3}agree_num\0\u{3}browse_num\0\u{3}video_time\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.picURL) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.toURL) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.type) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.agreeNum) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.browseNum) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.videoTime) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 1)
    }
    if !self.picURL.isEmpty {
      try visitor.visitSingularStringField(value: self.picURL, fieldNumber: 2)
    }
    if !self.toURL.isEmpty {
      try visitor.visitSingularStringField(value: self.toURL, fieldNumber: 3)
    }
    if self.type != 0 {
      try visitor.visitSingularInt32Field(value: self.type, fieldNumber: 4)
    }
    if self.agreeNum != 0 {
      try visitor.visitSingularInt64Field(value: self.agreeNum, fieldNumber: 5)
    }
    if self.browseNum != 0 {
      try visitor.visitSingularInt64Field(value: self.browseNum, fieldNumber: 6)
    }
    if self.videoTime != 0 {
      try visitor.visitSingularInt64Field(value: self.videoTime, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_GetForumDetail_UniversityInfo, rhs: Tieba_GetForumDetail_UniversityInfo) -> Bool {
    if lhs.title != rhs.title {return false}
    if lhs.picURL != rhs.picURL {return false}
    if lhs.toURL != rhs.toURL {return false}
    if lhs.type != rhs.type {return false}
    if lhs.agreeNum != rhs.agreeNum {return false}
    if lhs.browseNum != rhs.browseNum {return false}
    if lhs.videoTime != rhs.videoTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
