// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: GodInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_GodInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 = 0

  var intro: String = String()

  var type: Int32 = 0

  var fid: Int64 = 0

  var followed: Int32 = 0

  var recommendReason: String = String()

  var forumName: String = String()

  var canSendMsg: Int32 = 0

  var prefix: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_GodInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GodInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}intro\0\u{1}type\0\u{1}fid\0\u{1}followed\0\u{3}recommend_reason\0\u{3}forum_name\0\u{3}can_send_msg\0\u{1}prefix\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.intro) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.type) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.fid) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.followed) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.recommendReason) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.forumName) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.canSendMsg) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.prefix) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.intro.isEmpty {
      try visitor.visitSingularStringField(value: self.intro, fieldNumber: 2)
    }
    if self.type != 0 {
      try visitor.visitSingularInt32Field(value: self.type, fieldNumber: 3)
    }
    if self.fid != 0 {
      try visitor.visitSingularInt64Field(value: self.fid, fieldNumber: 4)
    }
    if self.followed != 0 {
      try visitor.visitSingularInt32Field(value: self.followed, fieldNumber: 5)
    }
    if !self.recommendReason.isEmpty {
      try visitor.visitSingularStringField(value: self.recommendReason, fieldNumber: 6)
    }
    if !self.forumName.isEmpty {
      try visitor.visitSingularStringField(value: self.forumName, fieldNumber: 7)
    }
    if self.canSendMsg != 0 {
      try visitor.visitSingularInt32Field(value: self.canSendMsg, fieldNumber: 8)
    }
    if !self.prefix.isEmpty {
      try visitor.visitSingularStringField(value: self.prefix, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_GodInfo, rhs: Tieba_GodInfo) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.intro != rhs.intro {return false}
    if lhs.type != rhs.type {return false}
    if lhs.fid != rhs.fid {return false}
    if lhs.followed != rhs.followed {return false}
    if lhs.recommendReason != rhs.recommendReason {return false}
    if lhs.forumName != rhs.forumName {return false}
    if lhs.canSendMsg != rhs.canSendMsg {return false}
    if lhs.prefix != rhs.prefix {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
