// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: GoodsInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_GoodsInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int32 {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var userName: String {
    get {_storage._userName}
    set {_uniqueStorage()._userName = newValue}
  }

  var userPortrait: String {
    get {_storage._userPortrait}
    set {_uniqueStorage()._userPortrait = newValue}
  }

  var threadTitle: String {
    get {_storage._threadTitle}
    set {_uniqueStorage()._threadTitle = newValue}
  }

  var threadPic: String {
    get {_storage._threadPic}
    set {_uniqueStorage()._threadPic = newValue}
  }

  var popWindowText: String {
    get {_storage._popWindowText}
    set {_uniqueStorage()._popWindowText = newValue}
  }

  var goodsStyle: Int32 {
    get {_storage._goodsStyle}
    set {_uniqueStorage()._goodsStyle = newValue}
  }

  var threadPicList: [Tieba_ThreadPicList] {
    get {_storage._threadPicList}
    set {_uniqueStorage()._threadPicList = newValue}
  }

  var labelVisible: Int32 {
    get {_storage._labelVisible}
    set {_uniqueStorage()._labelVisible = newValue}
  }

  var labelText: String {
    get {_storage._labelText}
    set {_uniqueStorage()._labelText = newValue}
  }

  var rankLevel: Int32 {
    get {_storage._rankLevel}
    set {_uniqueStorage()._rankLevel = newValue}
  }

  var threadType: String {
    get {_storage._threadType}
    set {_uniqueStorage()._threadType = newValue}
  }

  var buttonText: String {
    get {_storage._buttonText}
    set {_uniqueStorage()._buttonText = newValue}
  }

  var cardDesc: String {
    get {_storage._cardDesc}
    set {_uniqueStorage()._cardDesc = newValue}
  }

  var cardTag: String {
    get {_storage._cardTag}
    set {_uniqueStorage()._cardTag = newValue}
  }

  var width: Int32 {
    get {_storage._width}
    set {_uniqueStorage()._width = newValue}
  }

  var height: Int32 {
    get {_storage._height}
    set {_uniqueStorage()._height = newValue}
  }

  var labelMeasure: Int32 {
    get {_storage._labelMeasure}
    set {_uniqueStorage()._labelMeasure = newValue}
  }

  var threadContent: String {
    get {_storage._threadContent}
    set {_uniqueStorage()._threadContent = newValue}
  }

  var legoCard: String {
    get {_storage._legoCard}
    set {_uniqueStorage()._legoCard = newValue}
  }

  var videoInfo: Tieba_VideoInfo {
    get {_storage._videoInfo ?? Tieba_VideoInfo()}
    set {_uniqueStorage()._videoInfo = newValue}
  }
  /// Returns true if `videoInfo` has been explicitly set.
  var hasVideoInfo: Bool {_storage._videoInfo != nil}
  /// Clears the value of `videoInfo`. Subsequent reads from it will return its default value.
  mutating func clearVideoInfo() {_uniqueStorage()._videoInfo = nil}

  var tagName: String {
    get {_storage._tagName}
    set {_uniqueStorage()._tagName = newValue}
  }

  var buttonURL: String {
    get {_storage._buttonURL}
    set {_uniqueStorage()._buttonURL = newValue}
  }

  var adSource: String {
    get {_storage._adSource}
    set {_uniqueStorage()._adSource = newValue}
  }

  var tagNameURL: String {
    get {_storage._tagNameURL}
    set {_uniqueStorage()._tagNameURL = newValue}
  }

  var tagNameWh: String {
    get {_storage._tagNameWh}
    set {_uniqueStorage()._tagNameWh = newValue}
  }

  var brandIcon: String {
    get {_storage._brandIcon}
    set {_uniqueStorage()._brandIcon = newValue}
  }

  var brandIconWh: String {
    get {_storage._brandIconWh}
    set {_uniqueStorage()._brandIconWh = newValue}
  }

  var closeInfo: Tieba_AdCloseInfo {
    get {_storage._closeInfo ?? Tieba_AdCloseInfo()}
    set {_uniqueStorage()._closeInfo = newValue}
  }
  /// Returns true if `closeInfo` has been explicitly set.
  var hasCloseInfo: Bool {_storage._closeInfo != nil}
  /// Clears the value of `closeInfo`. Subsequent reads from it will return its default value.
  mutating func clearCloseInfo() {_uniqueStorage()._closeInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_GoodsInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GoodsInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}user_name\0\u{3}user_portrait\0\u{3}thread_title\0\u{3}thread_pic\0\u{3}pop_window_text\0\u{3}goods_style\0\u{3}thread_pic_list\0\u{3}label_visible\0\u{3}label_text\0\u{3}rank_level\0\u{3}thread_type\0\u{3}button_text\0\u{3}card_desc\0\u{3}card_tag\0\u{1}width\0\u{1}height\0\u{3}label_measure\0\u{3}thread_content\0\u{3}lego_card\0\u{3}video_info\0\u{3}tag_name\0\u{3}button_url\0\u{3}ad_source\0\u{3}tag_name_url\0\u{3}tag_name_wh\0\u{3}brand_icon\0\u{3}brand_icon_wh\0\u{3}close_info\0")

  fileprivate class _StorageClass {
    var _id: Int32 = 0
    var _userName: String = String()
    var _userPortrait: String = String()
    var _threadTitle: String = String()
    var _threadPic: String = String()
    var _popWindowText: String = String()
    var _goodsStyle: Int32 = 0
    var _threadPicList: [Tieba_ThreadPicList] = []
    var _labelVisible: Int32 = 0
    var _labelText: String = String()
    var _rankLevel: Int32 = 0
    var _threadType: String = String()
    var _buttonText: String = String()
    var _cardDesc: String = String()
    var _cardTag: String = String()
    var _width: Int32 = 0
    var _height: Int32 = 0
    var _labelMeasure: Int32 = 0
    var _threadContent: String = String()
    var _legoCard: String = String()
    var _videoInfo: Tieba_VideoInfo? = nil
    var _tagName: String = String()
    var _buttonURL: String = String()
    var _adSource: String = String()
    var _tagNameURL: String = String()
    var _tagNameWh: String = String()
    var _brandIcon: String = String()
    var _brandIconWh: String = String()
    var _closeInfo: Tieba_AdCloseInfo? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _userName = source._userName
      _userPortrait = source._userPortrait
      _threadTitle = source._threadTitle
      _threadPic = source._threadPic
      _popWindowText = source._popWindowText
      _goodsStyle = source._goodsStyle
      _threadPicList = source._threadPicList
      _labelVisible = source._labelVisible
      _labelText = source._labelText
      _rankLevel = source._rankLevel
      _threadType = source._threadType
      _buttonText = source._buttonText
      _cardDesc = source._cardDesc
      _cardTag = source._cardTag
      _width = source._width
      _height = source._height
      _labelMeasure = source._labelMeasure
      _threadContent = source._threadContent
      _legoCard = source._legoCard
      _videoInfo = source._videoInfo
      _tagName = source._tagName
      _buttonURL = source._buttonURL
      _adSource = source._adSource
      _tagNameURL = source._tagNameURL
      _tagNameWh = source._tagNameWh
      _brandIcon = source._brandIcon
      _brandIconWh = source._brandIconWh
      _closeInfo = source._closeInfo
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._userName) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._userPortrait) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._threadTitle) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._threadPic) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._popWindowText) }()
        case 7: try { try decoder.decodeSingularInt32Field(value: &_storage._goodsStyle) }()
        case 8: try { try decoder.decodeRepeatedMessageField(value: &_storage._threadPicList) }()
        case 9: try { try decoder.decodeSingularInt32Field(value: &_storage._labelVisible) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._labelText) }()
        case 11: try { try decoder.decodeSingularInt32Field(value: &_storage._rankLevel) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._threadType) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._buttonText) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._cardDesc) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._cardTag) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._width) }()
        case 17: try { try decoder.decodeSingularInt32Field(value: &_storage._height) }()
        case 18: try { try decoder.decodeSingularInt32Field(value: &_storage._labelMeasure) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._threadContent) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._legoCard) }()
        case 21: try { try decoder.decodeSingularMessageField(value: &_storage._videoInfo) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._tagName) }()
        case 23: try { try decoder.decodeSingularStringField(value: &_storage._buttonURL) }()
        case 24: try { try decoder.decodeSingularStringField(value: &_storage._adSource) }()
        case 25: try { try decoder.decodeSingularStringField(value: &_storage._tagNameURL) }()
        case 26: try { try decoder.decodeSingularStringField(value: &_storage._tagNameWh) }()
        case 27: try { try decoder.decodeSingularStringField(value: &_storage._brandIcon) }()
        case 28: try { try decoder.decodeSingularStringField(value: &_storage._brandIconWh) }()
        case 29: try { try decoder.decodeSingularMessageField(value: &_storage._closeInfo) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._id != 0 {
        try visitor.visitSingularInt32Field(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._userName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._userName, fieldNumber: 2)
      }
      if !_storage._userPortrait.isEmpty {
        try visitor.visitSingularStringField(value: _storage._userPortrait, fieldNumber: 3)
      }
      if !_storage._threadTitle.isEmpty {
        try visitor.visitSingularStringField(value: _storage._threadTitle, fieldNumber: 4)
      }
      if !_storage._threadPic.isEmpty {
        try visitor.visitSingularStringField(value: _storage._threadPic, fieldNumber: 5)
      }
      if !_storage._popWindowText.isEmpty {
        try visitor.visitSingularStringField(value: _storage._popWindowText, fieldNumber: 6)
      }
      if _storage._goodsStyle != 0 {
        try visitor.visitSingularInt32Field(value: _storage._goodsStyle, fieldNumber: 7)
      }
      if !_storage._threadPicList.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._threadPicList, fieldNumber: 8)
      }
      if _storage._labelVisible != 0 {
        try visitor.visitSingularInt32Field(value: _storage._labelVisible, fieldNumber: 9)
      }
      if !_storage._labelText.isEmpty {
        try visitor.visitSingularStringField(value: _storage._labelText, fieldNumber: 10)
      }
      if _storage._rankLevel != 0 {
        try visitor.visitSingularInt32Field(value: _storage._rankLevel, fieldNumber: 11)
      }
      if !_storage._threadType.isEmpty {
        try visitor.visitSingularStringField(value: _storage._threadType, fieldNumber: 12)
      }
      if !_storage._buttonText.isEmpty {
        try visitor.visitSingularStringField(value: _storage._buttonText, fieldNumber: 13)
      }
      if !_storage._cardDesc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cardDesc, fieldNumber: 14)
      }
      if !_storage._cardTag.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cardTag, fieldNumber: 15)
      }
      if _storage._width != 0 {
        try visitor.visitSingularInt32Field(value: _storage._width, fieldNumber: 16)
      }
      if _storage._height != 0 {
        try visitor.visitSingularInt32Field(value: _storage._height, fieldNumber: 17)
      }
      if _storage._labelMeasure != 0 {
        try visitor.visitSingularInt32Field(value: _storage._labelMeasure, fieldNumber: 18)
      }
      if !_storage._threadContent.isEmpty {
        try visitor.visitSingularStringField(value: _storage._threadContent, fieldNumber: 19)
      }
      if !_storage._legoCard.isEmpty {
        try visitor.visitSingularStringField(value: _storage._legoCard, fieldNumber: 20)
      }
      try { if let v = _storage._videoInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      } }()
      if !_storage._tagName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tagName, fieldNumber: 22)
      }
      if !_storage._buttonURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._buttonURL, fieldNumber: 23)
      }
      if !_storage._adSource.isEmpty {
        try visitor.visitSingularStringField(value: _storage._adSource, fieldNumber: 24)
      }
      if !_storage._tagNameURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tagNameURL, fieldNumber: 25)
      }
      if !_storage._tagNameWh.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tagNameWh, fieldNumber: 26)
      }
      if !_storage._brandIcon.isEmpty {
        try visitor.visitSingularStringField(value: _storage._brandIcon, fieldNumber: 27)
      }
      if !_storage._brandIconWh.isEmpty {
        try visitor.visitSingularStringField(value: _storage._brandIconWh, fieldNumber: 28)
      }
      try { if let v = _storage._closeInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 29)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_GoodsInfo, rhs: Tieba_GoodsInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._userName != rhs_storage._userName {return false}
        if _storage._userPortrait != rhs_storage._userPortrait {return false}
        if _storage._threadTitle != rhs_storage._threadTitle {return false}
        if _storage._threadPic != rhs_storage._threadPic {return false}
        if _storage._popWindowText != rhs_storage._popWindowText {return false}
        if _storage._goodsStyle != rhs_storage._goodsStyle {return false}
        if _storage._threadPicList != rhs_storage._threadPicList {return false}
        if _storage._labelVisible != rhs_storage._labelVisible {return false}
        if _storage._labelText != rhs_storage._labelText {return false}
        if _storage._rankLevel != rhs_storage._rankLevel {return false}
        if _storage._threadType != rhs_storage._threadType {return false}
        if _storage._buttonText != rhs_storage._buttonText {return false}
        if _storage._cardDesc != rhs_storage._cardDesc {return false}
        if _storage._cardTag != rhs_storage._cardTag {return false}
        if _storage._width != rhs_storage._width {return false}
        if _storage._height != rhs_storage._height {return false}
        if _storage._labelMeasure != rhs_storage._labelMeasure {return false}
        if _storage._threadContent != rhs_storage._threadContent {return false}
        if _storage._legoCard != rhs_storage._legoCard {return false}
        if _storage._videoInfo != rhs_storage._videoInfo {return false}
        if _storage._tagName != rhs_storage._tagName {return false}
        if _storage._buttonURL != rhs_storage._buttonURL {return false}
        if _storage._adSource != rhs_storage._adSource {return false}
        if _storage._tagNameURL != rhs_storage._tagNameURL {return false}
        if _storage._tagNameWh != rhs_storage._tagNameWh {return false}
        if _storage._brandIcon != rhs_storage._brandIcon {return false}
        if _storage._brandIconWh != rhs_storage._brandIconWh {return false}
        if _storage._closeInfo != rhs_storage._closeInfo {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
