// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: GuessLikeThreadInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_GuessLikeThreadInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var threadID: Int64 = 0

  var forumID: Int64 = 0

  var forumName: String = String()

  var replyNum: Int64 = 0

  var recomCover: String = String()

  var recomReason: String = String()

  var title: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_GuessLikeThreadInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GuessLikeThreadInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}thread_id\0\u{3}forum_id\0\u{3}forum_name\0\u{3}reply_num\0\u{3}recom_cover\0\u{3}recom_reason\0\u{1}title\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.threadID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.forumID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.forumName) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.replyNum) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.recomCover) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.recomReason) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.title) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.threadID != 0 {
      try visitor.visitSingularInt64Field(value: self.threadID, fieldNumber: 1)
    }
    if self.forumID != 0 {
      try visitor.visitSingularInt64Field(value: self.forumID, fieldNumber: 2)
    }
    if !self.forumName.isEmpty {
      try visitor.visitSingularStringField(value: self.forumName, fieldNumber: 3)
    }
    if self.replyNum != 0 {
      try visitor.visitSingularInt64Field(value: self.replyNum, fieldNumber: 4)
    }
    if !self.recomCover.isEmpty {
      try visitor.visitSingularStringField(value: self.recomCover, fieldNumber: 5)
    }
    if !self.recomReason.isEmpty {
      try visitor.visitSingularStringField(value: self.recomReason, fieldNumber: 6)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_GuessLikeThreadInfo, rhs: Tieba_GuessLikeThreadInfo) -> Bool {
    if lhs.threadID != rhs.threadID {return false}
    if lhs.forumID != rhs.forumID {return false}
    if lhs.forumName != rhs.forumName {return false}
    if lhs.replyNum != rhs.replyNum {return false}
    if lhs.recomCover != rhs.recomCover {return false}
    if lhs.recomReason != rhs.recomReason {return false}
    if lhs.title != rhs.title {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
