// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: HotPost.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_HotPost: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var threadID: UInt64 = 0

  var postID: UInt64 = 0

  var userName: String = String()

  var userID: UInt64 = 0

  var postZan: Tieba_PbPostZan {
    get {_postZan ?? Tieba_PbPostZan()}
    set {_postZan = newValue}
  }
  /// Returns true if `postZan` has been explicitly set.
  var hasPostZan: Bool {self._postZan != nil}
  /// Clears the value of `postZan`. Subsequent reads from it will return its default value.
  mutating func clearPostZan() {self._postZan = nil}

  var postNum: Int32 = 0

  var content: [Tieba_PbContent] = []

  var createTime: UInt32 = 0

  var floor: UInt32 = 0

  var portrait: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _postZan: Tieba_PbPostZan? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_HotPost: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HotPost"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}thread_id\0\u{3}post_id\0\u{3}user_name\0\u{3}user_id\0\u{3}post_zan\0\u{3}post_num\0\u{1}content\0\u{3}create_time\0\u{1}floor\0\u{1}portrait\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.threadID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.postID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.userName) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.userID) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._postZan) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.postNum) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.content) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.createTime) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.floor) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.portrait) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.threadID != 0 {
      try visitor.visitSingularUInt64Field(value: self.threadID, fieldNumber: 1)
    }
    if self.postID != 0 {
      try visitor.visitSingularUInt64Field(value: self.postID, fieldNumber: 2)
    }
    if !self.userName.isEmpty {
      try visitor.visitSingularStringField(value: self.userName, fieldNumber: 3)
    }
    if self.userID != 0 {
      try visitor.visitSingularUInt64Field(value: self.userID, fieldNumber: 4)
    }
    try { if let v = self._postZan {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.postNum != 0 {
      try visitor.visitSingularInt32Field(value: self.postNum, fieldNumber: 6)
    }
    if !self.content.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.content, fieldNumber: 7)
    }
    if self.createTime != 0 {
      try visitor.visitSingularUInt32Field(value: self.createTime, fieldNumber: 8)
    }
    if self.floor != 0 {
      try visitor.visitSingularUInt32Field(value: self.floor, fieldNumber: 9)
    }
    if !self.portrait.isEmpty {
      try visitor.visitSingularStringField(value: self.portrait, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_HotPost, rhs: Tieba_HotPost) -> Bool {
    if lhs.threadID != rhs.threadID {return false}
    if lhs.postID != rhs.postID {return false}
    if lhs.userName != rhs.userName {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs._postZan != rhs._postZan {return false}
    if lhs.postNum != rhs.postNum {return false}
    if lhs.content != rhs.content {return false}
    if lhs.createTime != rhs.createTime {return false}
    if lhs.floor != rhs.floor {return false}
    if lhs.portrait != rhs.portrait {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
