// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Icon.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Icon: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var weight: Int32 = 0

  var url: String = String()

  var icon: String = String()

  var value: Int32 = 0

  var terminal: Tieba_Terminal {
    get {_terminal ?? Tieba_Terminal()}
    set {_terminal = newValue}
  }
  /// Returns true if `terminal` has been explicitly set.
  var hasTerminal: Bool {self._terminal != nil}
  /// Clears the value of `terminal`. Subsequent reads from it will return its default value.
  mutating func clearTerminal() {self._terminal = nil}

  var position: Tieba_Position {
    get {_position ?? Tieba_Position()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  mutating func clearPosition() {self._position = nil}

  var spriteInfo: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _terminal: Tieba_Terminal? = nil
  fileprivate var _position: Tieba_Position? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_Icon: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Icon"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}weight\0\u{1}url\0\u{1}icon\0\u{1}value\0\u{1}terminal\0\u{1}position\0\u{3}sprite_info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.weight) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.icon) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.value) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._terminal) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.spriteInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.weight != 0 {
      try visitor.visitSingularInt32Field(value: self.weight, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.icon.isEmpty {
      try visitor.visitSingularStringField(value: self.icon, fieldNumber: 4)
    }
    if self.value != 0 {
      try visitor.visitSingularInt32Field(value: self.value, fieldNumber: 5)
    }
    try { if let v = self._terminal {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if !self.spriteInfo.isEmpty {
      try visitor.visitRepeatedStringField(value: self.spriteInfo, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Icon, rhs: Tieba_Icon) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.weight != rhs.weight {return false}
    if lhs.url != rhs.url {return false}
    if lhs.icon != rhs.icon {return false}
    if lhs.value != rhs.value {return false}
    if lhs._terminal != rhs._terminal {return false}
    if lhs._position != rhs._position {return false}
    if lhs.spriteInfo != rhs.spriteInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
