// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ManagerElection.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_ManagerElection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var canVote: UInt32 = 0

  var voteNum: UInt32 = 0

  var beginVoteTime: UInt32 = 0

  var voteCondition: [String] = []

  var tailText: String = String()

  var isShowDistribute: UInt32 = 0

  var remainderTime: UInt32 = 0

  var status: UInt32 = 0

  var voteConditionTitle: [String] = []

  var voteConditionPic: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_ManagerElection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ManagerElection"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}can_vote\0\u{3}vote_num\0\u{3}begin_vote_time\0\u{4}\u{2}vote_condition\0\u{3}tail_text\0\u{3}is_show_distribute\0\u{3}remainder_time\0\u{1}status\0\u{3}vote_condition_title\0\u{3}vote_condition_pic\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.canVote) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.voteNum) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.beginVoteTime) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.voteCondition) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.tailText) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.isShowDistribute) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.remainderTime) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.status) }()
      case 10: try { try decoder.decodeRepeatedStringField(value: &self.voteConditionTitle) }()
      case 11: try { try decoder.decodeRepeatedStringField(value: &self.voteConditionPic) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.canVote != 0 {
      try visitor.visitSingularUInt32Field(value: self.canVote, fieldNumber: 1)
    }
    if self.voteNum != 0 {
      try visitor.visitSingularUInt32Field(value: self.voteNum, fieldNumber: 2)
    }
    if self.beginVoteTime != 0 {
      try visitor.visitSingularUInt32Field(value: self.beginVoteTime, fieldNumber: 3)
    }
    if !self.voteCondition.isEmpty {
      try visitor.visitRepeatedStringField(value: self.voteCondition, fieldNumber: 5)
    }
    if !self.tailText.isEmpty {
      try visitor.visitSingularStringField(value: self.tailText, fieldNumber: 6)
    }
    if self.isShowDistribute != 0 {
      try visitor.visitSingularUInt32Field(value: self.isShowDistribute, fieldNumber: 7)
    }
    if self.remainderTime != 0 {
      try visitor.visitSingularUInt32Field(value: self.remainderTime, fieldNumber: 8)
    }
    if self.status != 0 {
      try visitor.visitSingularUInt32Field(value: self.status, fieldNumber: 9)
    }
    if !self.voteConditionTitle.isEmpty {
      try visitor.visitRepeatedStringField(value: self.voteConditionTitle, fieldNumber: 10)
    }
    if !self.voteConditionPic.isEmpty {
      try visitor.visitRepeatedStringField(value: self.voteConditionPic, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_ManagerElection, rhs: Tieba_ManagerElection) -> Bool {
    if lhs.canVote != rhs.canVote {return false}
    if lhs.voteNum != rhs.voteNum {return false}
    if lhs.beginVoteTime != rhs.beginVoteTime {return false}
    if lhs.voteCondition != rhs.voteCondition {return false}
    if lhs.tailText != rhs.tailText {return false}
    if lhs.isShowDistribute != rhs.isShowDistribute {return false}
    if lhs.remainderTime != rhs.remainderTime {return false}
    if lhs.status != rhs.status {return false}
    if lhs.voteConditionTitle != rhs.voteConditionTitle {return false}
    if lhs.voteConditionPic != rhs.voteConditionPic {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
