// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Media.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Media: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Int32 = 0

  var bigPic: String = String()

  var srcPic: String = String()

  var width: UInt32 = 0

  var height: UInt32 = 0

  var originPic: String = String()

  var originSize: UInt32 = 0

  var postID: Int64 = 0

  var dynamicPic: String = String()

  var isLongPic: UInt32 = 0

  var showOriginalBtn: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_Media: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Media"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{2}\u{2}bigPic\0\u{2}\u{5}srcPic\0\u{2}\u{2}width\0\u{1}height\0\u{2}\u{4}originPic\0\u{1}originSize\0\u{1}postId\0\u{1}dynamicPic\0\u{1}isLongPic\0\u{1}showOriginalBtn\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.type) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.bigPic) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.srcPic) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 15: try { try decoder.decodeSingularStringField(value: &self.originPic) }()
      case 16: try { try decoder.decodeSingularUInt32Field(value: &self.originSize) }()
      case 17: try { try decoder.decodeSingularInt64Field(value: &self.postID) }()
      case 18: try { try decoder.decodeSingularStringField(value: &self.dynamicPic) }()
      case 19: try { try decoder.decodeSingularUInt32Field(value: &self.isLongPic) }()
      case 20: try { try decoder.decodeSingularUInt32Field(value: &self.showOriginalBtn) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != 0 {
      try visitor.visitSingularInt32Field(value: self.type, fieldNumber: 1)
    }
    if !self.bigPic.isEmpty {
      try visitor.visitSingularStringField(value: self.bigPic, fieldNumber: 3)
    }
    if !self.srcPic.isEmpty {
      try visitor.visitSingularStringField(value: self.srcPic, fieldNumber: 8)
    }
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 10)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 11)
    }
    if !self.originPic.isEmpty {
      try visitor.visitSingularStringField(value: self.originPic, fieldNumber: 15)
    }
    if self.originSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.originSize, fieldNumber: 16)
    }
    if self.postID != 0 {
      try visitor.visitSingularInt64Field(value: self.postID, fieldNumber: 17)
    }
    if !self.dynamicPic.isEmpty {
      try visitor.visitSingularStringField(value: self.dynamicPic, fieldNumber: 18)
    }
    if self.isLongPic != 0 {
      try visitor.visitSingularUInt32Field(value: self.isLongPic, fieldNumber: 19)
    }
    if self.showOriginalBtn != 0 {
      try visitor.visitSingularUInt32Field(value: self.showOriginalBtn, fieldNumber: 20)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Media, rhs: Tieba_Media) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.bigPic != rhs.bigPic {return false}
    if lhs.srcPic != rhs.srcPic {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.originPic != rhs.originPic {return false}
    if lhs.originSize != rhs.originSize {return false}
    if lhs.postID != rhs.postID {return false}
    if lhs.dynamicPic != rhs.dynamicPic {return false}
    if lhs.isLongPic != rhs.isLongPic {return false}
    if lhs.showOriginalBtn != rhs.showOriginalBtn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
