// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: MemeInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_MemeInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pckID: UInt32 = 0

  var picID: UInt64 = 0

  var picURL: String = String()

  var thumbnail: String = String()

  var width: UInt32 = 0

  var height: UInt32 = 0

  var detailLink: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_MemeInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MemeInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pckId\0\u{1}picId\0\u{1}picUrl\0\u{1}thumbnail\0\u{1}width\0\u{1}height\0\u{1}detailLink\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.pckID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.picID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.picURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.thumbnail) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.detailLink) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pckID != 0 {
      try visitor.visitSingularUInt32Field(value: self.pckID, fieldNumber: 1)
    }
    if self.picID != 0 {
      try visitor.visitSingularUInt64Field(value: self.picID, fieldNumber: 2)
    }
    if !self.picURL.isEmpty {
      try visitor.visitSingularStringField(value: self.picURL, fieldNumber: 3)
    }
    if !self.thumbnail.isEmpty {
      try visitor.visitSingularStringField(value: self.thumbnail, fieldNumber: 4)
    }
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 5)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 6)
    }
    if !self.detailLink.isEmpty {
      try visitor.visitSingularStringField(value: self.detailLink, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_MemeInfo, rhs: Tieba_MemeInfo) -> Bool {
    if lhs.pckID != rhs.pckID {return false}
    if lhs.picID != rhs.picID {return false}
    if lhs.picURL != rhs.picURL {return false}
    if lhs.thumbnail != rhs.thumbnail {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.detailLink != rhs.detailLink {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
