// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ModuleInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_ModuleInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var moduleList: [Tieba_ThreadModule] = []

  var maxModuleNum: Int32 = 0

  var maxModuleThreadNum: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_ModuleInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ModuleInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}module_list\0\u{3}max_module_num\0\u{3}max_module_thread_num\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.moduleList) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.maxModuleNum) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.maxModuleThreadNum) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.moduleList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.moduleList, fieldNumber: 1)
    }
    if self.maxModuleNum != 0 {
      try visitor.visitSingularInt32Field(value: self.maxModuleNum, fieldNumber: 2)
    }
    if self.maxModuleThreadNum != 0 {
      try visitor.visitSingularInt32Field(value: self.maxModuleThreadNum, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_ModuleInfo, rhs: Tieba_ModuleInfo) -> Bool {
    if lhs.moduleList != rhs.moduleList {return false}
    if lhs.maxModuleNum != rhs.maxModuleNum {return false}
    if lhs.maxModuleThreadNum != rhs.maxModuleThreadNum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
