// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: MultipleForum.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_MultipleForum: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var forumID: Int64 = 0

  var forumName: String = String()

  var isBawu: Int32 = 0

  var bawuType: String = String()

  var isDeleted: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_MultipleForum: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MultipleForum"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}forum_id\0\u{3}forum_name\0\u{3}is_bawu\0\u{3}bawu_type\0\u{3}is_deleted\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.forumID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.forumName) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.isBawu) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.bawuType) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.isDeleted) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.forumID != 0 {
      try visitor.visitSingularInt64Field(value: self.forumID, fieldNumber: 1)
    }
    if !self.forumName.isEmpty {
      try visitor.visitSingularStringField(value: self.forumName, fieldNumber: 2)
    }
    if self.isBawu != 0 {
      try visitor.visitSingularInt32Field(value: self.isBawu, fieldNumber: 3)
    }
    if !self.bawuType.isEmpty {
      try visitor.visitSingularStringField(value: self.bawuType, fieldNumber: 4)
    }
    if self.isDeleted != 0 {
      try visitor.visitSingularInt32Field(value: self.isDeleted, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_MultipleForum, rhs: Tieba_MultipleForum) -> Bool {
    if lhs.forumID != rhs.forumID {return false}
    if lhs.forumName != rhs.forumName {return false}
    if lhs.isBawu != rhs.isBawu {return false}
    if lhs.bawuType != rhs.bawuType {return false}
    if lhs.isDeleted != rhs.isDeleted {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
