// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: OriginThreadInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_OriginThreadInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var title: String {
    get {_storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  var media: [Tieba_Media] {
    get {_storage._media}
    set {_uniqueStorage()._media = newValue}
  }

  var abstract: [Tieba_Abstract] {
    get {_storage._abstract}
    set {_uniqueStorage()._abstract = newValue}
  }

  var fname: String {
    get {_storage._fname}
    set {_uniqueStorage()._fname = newValue}
  }

  var tid: String {
    get {_storage._tid}
    set {_uniqueStorage()._tid = newValue}
  }

  var alaInfo: Tieba_AlaLiveInfo {
    get {_storage._alaInfo ?? Tieba_AlaLiveInfo()}
    set {_uniqueStorage()._alaInfo = newValue}
  }
  /// Returns true if `alaInfo` has been explicitly set.
  var hasAlaInfo: Bool {_storage._alaInfo != nil}
  /// Clears the value of `alaInfo`. Subsequent reads from it will return its default value.
  mutating func clearAlaInfo() {_uniqueStorage()._alaInfo = nil}

  var fid: Int64 {
    get {_storage._fid}
    set {_uniqueStorage()._fid = newValue}
  }

  var threadType: Int32 {
    get {_storage._threadType}
    set {_uniqueStorage()._threadType = newValue}
  }

  var isDeleted: Int32 {
    get {_storage._isDeleted}
    set {_uniqueStorage()._isDeleted = newValue}
  }

  var isUgc: Int32 {
    get {_storage._isUgc}
    set {_uniqueStorage()._isUgc = newValue}
  }

  var oriUgcInfo: Tieba_Baijiahao {
    get {_storage._oriUgcInfo ?? Tieba_Baijiahao()}
    set {_uniqueStorage()._oriUgcInfo = newValue}
  }
  /// Returns true if `oriUgcInfo` has been explicitly set.
  var hasOriUgcInfo: Bool {_storage._oriUgcInfo != nil}
  /// Clears the value of `oriUgcInfo`. Subsequent reads from it will return its default value.
  mutating func clearOriUgcInfo() {_uniqueStorage()._oriUgcInfo = nil}

  var voiceInfo: [Tieba_Voice] {
    get {_storage._voiceInfo}
    set {_uniqueStorage()._voiceInfo = newValue}
  }

  var videoInfo: Tieba_VideoInfo {
    get {_storage._videoInfo ?? Tieba_VideoInfo()}
    set {_uniqueStorage()._videoInfo = newValue}
  }
  /// Returns true if `videoInfo` has been explicitly set.
  var hasVideoInfo: Bool {_storage._videoInfo != nil}
  /// Clears the value of `videoInfo`. Subsequent reads from it will return its default value.
  mutating func clearVideoInfo() {_uniqueStorage()._videoInfo = nil}

  var content: [Tieba_PbContent] {
    get {_storage._content}
    set {_uniqueStorage()._content = newValue}
  }

  var isNewStyle: Int32 {
    get {_storage._isNewStyle}
    set {_uniqueStorage()._isNewStyle = newValue}
  }

  var replyNum: Int32 {
    get {_storage._replyNum}
    set {_uniqueStorage()._replyNum = newValue}
  }

  var author: Tieba_User {
    get {_storage._author ?? Tieba_User()}
    set {_uniqueStorage()._author = newValue}
  }
  /// Returns true if `author` has been explicitly set.
  var hasAuthor: Bool {_storage._author != nil}
  /// Clears the value of `author`. Subsequent reads from it will return its default value.
  mutating func clearAuthor() {_uniqueStorage()._author = nil}

  var agree: Tieba_Agree {
    get {_storage._agree ?? Tieba_Agree()}
    set {_uniqueStorage()._agree = newValue}
  }
  /// Returns true if `agree` has been explicitly set.
  var hasAgree: Bool {_storage._agree != nil}
  /// Clears the value of `agree`. Subsequent reads from it will return its default value.
  mutating func clearAgree() {_uniqueStorage()._agree = nil}

  var sharedNum: Int32 {
    get {_storage._sharedNum}
    set {_uniqueStorage()._sharedNum = newValue}
  }

  var pollInfo: Tieba_PollInfo {
    get {_storage._pollInfo ?? Tieba_PollInfo()}
    set {_uniqueStorage()._pollInfo = newValue}
  }
  /// Returns true if `pollInfo` has been explicitly set.
  var hasPollInfo: Bool {_storage._pollInfo != nil}
  /// Clears the value of `pollInfo`. Subsequent reads from it will return its default value.
  mutating func clearPollInfo() {_uniqueStorage()._pollInfo = nil}

  var item: Tieba_Item {
    get {_storage._item ?? Tieba_Item()}
    set {_uniqueStorage()._item = newValue}
  }
  /// Returns true if `item` has been explicitly set.
  var hasItem: Bool {_storage._item != nil}
  /// Clears the value of `item`. Subsequent reads from it will return its default value.
  mutating func clearItem() {_uniqueStorage()._item = nil}

  var itemStar: [Tieba_HeadItem] {
    get {_storage._itemStar}
    set {_uniqueStorage()._itemStar = newValue}
  }

  var pbLinkInfo: [Tieba_PbLinkInfo] {
    get {_storage._pbLinkInfo}
    set {_uniqueStorage()._pbLinkInfo = newValue}
  }

  var pid: Int64 {
    get {_storage._pid}
    set {_uniqueStorage()._pid = newValue}
  }

  var goodTypes: Int32 {
    get {_storage._goodTypes}
    set {_uniqueStorage()._goodTypes = newValue}
  }

  var topTypes: Int32 {
    get {_storage._topTypes}
    set {_uniqueStorage()._topTypes = newValue}
  }

  var isFrsMask: Int32 {
    get {_storage._isFrsMask}
    set {_uniqueStorage()._isFrsMask = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_OriginThreadInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OriginThreadInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}media\0\u{3}_abstract\0\u{1}fname\0\u{1}tid\0\u{3}ala_info\0\u{1}fid\0\u{3}thread_type\0\u{3}is_deleted\0\u{3}is_ugc\0\u{3}ori_ugc_info\0\u{3}voice_info\0\u{3}video_info\0\u{1}content\0\u{3}is_new_style\0\u{3}reply_num\0\u{2}\u{2}author\0\u{1}agree\0\u{3}shared_num\0\u{3}poll_info\0\u{1}item\0\u{3}item_star\0\u{3}pb_link_info\0\u{1}pid\0\u{3}good_types\0\u{3}top_types\0\u{3}is_frs_mask\0")

  fileprivate class _StorageClass {
    var _title: String = String()
    var _media: [Tieba_Media] = []
    var _abstract: [Tieba_Abstract] = []
    var _fname: String = String()
    var _tid: String = String()
    var _alaInfo: Tieba_AlaLiveInfo? = nil
    var _fid: Int64 = 0
    var _threadType: Int32 = 0
    var _isDeleted: Int32 = 0
    var _isUgc: Int32 = 0
    var _oriUgcInfo: Tieba_Baijiahao? = nil
    var _voiceInfo: [Tieba_Voice] = []
    var _videoInfo: Tieba_VideoInfo? = nil
    var _content: [Tieba_PbContent] = []
    var _isNewStyle: Int32 = 0
    var _replyNum: Int32 = 0
    var _author: Tieba_User? = nil
    var _agree: Tieba_Agree? = nil
    var _sharedNum: Int32 = 0
    var _pollInfo: Tieba_PollInfo? = nil
    var _item: Tieba_Item? = nil
    var _itemStar: [Tieba_HeadItem] = []
    var _pbLinkInfo: [Tieba_PbLinkInfo] = []
    var _pid: Int64 = 0
    var _goodTypes: Int32 = 0
    var _topTypes: Int32 = 0
    var _isFrsMask: Int32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _title = source._title
      _media = source._media
      _abstract = source._abstract
      _fname = source._fname
      _tid = source._tid
      _alaInfo = source._alaInfo
      _fid = source._fid
      _threadType = source._threadType
      _isDeleted = source._isDeleted
      _isUgc = source._isUgc
      _oriUgcInfo = source._oriUgcInfo
      _voiceInfo = source._voiceInfo
      _videoInfo = source._videoInfo
      _content = source._content
      _isNewStyle = source._isNewStyle
      _replyNum = source._replyNum
      _author = source._author
      _agree = source._agree
      _sharedNum = source._sharedNum
      _pollInfo = source._pollInfo
      _item = source._item
      _itemStar = source._itemStar
      _pbLinkInfo = source._pbLinkInfo
      _pid = source._pid
      _goodTypes = source._goodTypes
      _topTypes = source._topTypes
      _isFrsMask = source._isFrsMask
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._media) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._abstract) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._fname) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._tid) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._alaInfo) }()
        case 7: try { try decoder.decodeSingularInt64Field(value: &_storage._fid) }()
        case 8: try { try decoder.decodeSingularInt32Field(value: &_storage._threadType) }()
        case 9: try { try decoder.decodeSingularInt32Field(value: &_storage._isDeleted) }()
        case 10: try { try decoder.decodeSingularInt32Field(value: &_storage._isUgc) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._oriUgcInfo) }()
        case 12: try { try decoder.decodeRepeatedMessageField(value: &_storage._voiceInfo) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._videoInfo) }()
        case 14: try { try decoder.decodeRepeatedMessageField(value: &_storage._content) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._isNewStyle) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._replyNum) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._author) }()
        case 19: try { try decoder.decodeSingularMessageField(value: &_storage._agree) }()
        case 20: try { try decoder.decodeSingularInt32Field(value: &_storage._sharedNum) }()
        case 21: try { try decoder.decodeSingularMessageField(value: &_storage._pollInfo) }()
        case 22: try { try decoder.decodeSingularMessageField(value: &_storage._item) }()
        case 23: try { try decoder.decodeRepeatedMessageField(value: &_storage._itemStar) }()
        case 24: try { try decoder.decodeRepeatedMessageField(value: &_storage._pbLinkInfo) }()
        case 25: try { try decoder.decodeSingularInt64Field(value: &_storage._pid) }()
        case 26: try { try decoder.decodeSingularInt32Field(value: &_storage._goodTypes) }()
        case 27: try { try decoder.decodeSingularInt32Field(value: &_storage._topTypes) }()
        case 28: try { try decoder.decodeSingularInt32Field(value: &_storage._isFrsMask) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 1)
      }
      if !_storage._media.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._media, fieldNumber: 2)
      }
      if !_storage._abstract.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._abstract, fieldNumber: 3)
      }
      if !_storage._fname.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fname, fieldNumber: 4)
      }
      if !_storage._tid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tid, fieldNumber: 5)
      }
      try { if let v = _storage._alaInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if _storage._fid != 0 {
        try visitor.visitSingularInt64Field(value: _storage._fid, fieldNumber: 7)
      }
      if _storage._threadType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._threadType, fieldNumber: 8)
      }
      if _storage._isDeleted != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isDeleted, fieldNumber: 9)
      }
      if _storage._isUgc != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isUgc, fieldNumber: 10)
      }
      try { if let v = _storage._oriUgcInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      if !_storage._voiceInfo.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._voiceInfo, fieldNumber: 12)
      }
      try { if let v = _storage._videoInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      if !_storage._content.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._content, fieldNumber: 14)
      }
      if _storage._isNewStyle != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isNewStyle, fieldNumber: 15)
      }
      if _storage._replyNum != 0 {
        try visitor.visitSingularInt32Field(value: _storage._replyNum, fieldNumber: 16)
      }
      try { if let v = _storage._author {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._agree {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 19)
      } }()
      if _storage._sharedNum != 0 {
        try visitor.visitSingularInt32Field(value: _storage._sharedNum, fieldNumber: 20)
      }
      try { if let v = _storage._pollInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      } }()
      try { if let v = _storage._item {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
      } }()
      if !_storage._itemStar.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._itemStar, fieldNumber: 23)
      }
      if !_storage._pbLinkInfo.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._pbLinkInfo, fieldNumber: 24)
      }
      if _storage._pid != 0 {
        try visitor.visitSingularInt64Field(value: _storage._pid, fieldNumber: 25)
      }
      if _storage._goodTypes != 0 {
        try visitor.visitSingularInt32Field(value: _storage._goodTypes, fieldNumber: 26)
      }
      if _storage._topTypes != 0 {
        try visitor.visitSingularInt32Field(value: _storage._topTypes, fieldNumber: 27)
      }
      if _storage._isFrsMask != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isFrsMask, fieldNumber: 28)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_OriginThreadInfo, rhs: Tieba_OriginThreadInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._title != rhs_storage._title {return false}
        if _storage._media != rhs_storage._media {return false}
        if _storage._abstract != rhs_storage._abstract {return false}
        if _storage._fname != rhs_storage._fname {return false}
        if _storage._tid != rhs_storage._tid {return false}
        if _storage._alaInfo != rhs_storage._alaInfo {return false}
        if _storage._fid != rhs_storage._fid {return false}
        if _storage._threadType != rhs_storage._threadType {return false}
        if _storage._isDeleted != rhs_storage._isDeleted {return false}
        if _storage._isUgc != rhs_storage._isUgc {return false}
        if _storage._oriUgcInfo != rhs_storage._oriUgcInfo {return false}
        if _storage._voiceInfo != rhs_storage._voiceInfo {return false}
        if _storage._videoInfo != rhs_storage._videoInfo {return false}
        if _storage._content != rhs_storage._content {return false}
        if _storage._isNewStyle != rhs_storage._isNewStyle {return false}
        if _storage._replyNum != rhs_storage._replyNum {return false}
        if _storage._author != rhs_storage._author {return false}
        if _storage._agree != rhs_storage._agree {return false}
        if _storage._sharedNum != rhs_storage._sharedNum {return false}
        if _storage._pollInfo != rhs_storage._pollInfo {return false}
        if _storage._item != rhs_storage._item {return false}
        if _storage._itemStar != rhs_storage._itemStar {return false}
        if _storage._pbLinkInfo != rhs_storage._pbLinkInfo {return false}
        if _storage._pid != rhs_storage._pid {return false}
        if _storage._goodTypes != rhs_storage._goodTypes {return false}
        if _storage._topTypes != rhs_storage._topTypes {return false}
        if _storage._isFrsMask != rhs_storage._isFrsMask {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
