// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PbContent.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PbContent: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Int32 {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  var text: String {
    get {_storage._text}
    set {_uniqueStorage()._text = newValue}
  }

  var link: String {
    get {_storage._link}
    set {_uniqueStorage()._link = newValue}
  }

  var src: String {
    get {_storage._src}
    set {_uniqueStorage()._src = newValue}
  }

  var bsize: String {
    get {_storage._bsize}
    set {_uniqueStorage()._bsize = newValue}
  }

  var bigSrc: String {
    get {_storage._bigSrc}
    set {_uniqueStorage()._bigSrc = newValue}
  }

  var bigSize: String {
    get {_storage._bigSize}
    set {_uniqueStorage()._bigSize = newValue}
  }

  var cdnSrc: String {
    get {_storage._cdnSrc}
    set {_uniqueStorage()._cdnSrc = newValue}
  }

  var bigCdnSrc: String {
    get {_storage._bigCdnSrc}
    set {_uniqueStorage()._bigCdnSrc = newValue}
  }

  var imgType: String {
    get {_storage._imgType}
    set {_uniqueStorage()._imgType = newValue}
  }

  var c: String {
    get {_storage._c}
    set {_uniqueStorage()._c = newValue}
  }

  var voiceMd5: String {
    get {_storage._voiceMd5}
    set {_uniqueStorage()._voiceMd5 = newValue}
  }

  var duringTime: UInt32 {
    get {_storage._duringTime}
    set {_uniqueStorage()._duringTime = newValue}
  }

  var uid: Int64 {
    get {_storage._uid}
    set {_uniqueStorage()._uid = newValue}
  }

  var dynamic: String {
    get {_storage._dynamic}
    set {_uniqueStorage()._dynamic = newValue}
  }

  var `static`: String {
    get {_storage._static}
    set {_uniqueStorage()._static = newValue}
  }

  var width: UInt32 {
    get {_storage._width}
    set {_uniqueStorage()._width = newValue}
  }

  var height: UInt32 {
    get {_storage._height}
    set {_uniqueStorage()._height = newValue}
  }

  var originSrc: String {
    get {_storage._originSrc}
    set {_uniqueStorage()._originSrc = newValue}
  }

  var originSize: UInt32 {
    get {_storage._originSize}
    set {_uniqueStorage()._originSize = newValue}
  }

  var mediaSubtitle: String {
    get {_storage._mediaSubtitle}
    set {_uniqueStorage()._mediaSubtitle = newValue}
  }

  var urlType: Int32 {
    get {_storage._urlType}
    set {_uniqueStorage()._urlType = newValue}
  }

  var memeInfo: Tieba_MemeInfo {
    get {_storage._memeInfo ?? Tieba_MemeInfo()}
    set {_uniqueStorage()._memeInfo = newValue}
  }
  /// Returns true if `memeInfo` has been explicitly set.
  var hasMemeInfo: Bool {_storage._memeInfo != nil}
  /// Clears the value of `memeInfo`. Subsequent reads from it will return its default value.
  mutating func clearMemeInfo() {_uniqueStorage()._memeInfo = nil}

  var isLongPic: UInt32 {
    get {_storage._isLongPic}
    set {_uniqueStorage()._isLongPic = newValue}
  }

  var showOriginalBtn: UInt32 {
    get {_storage._showOriginalBtn}
    set {_uniqueStorage()._showOriginalBtn = newValue}
  }

  var cdnSrcActive: String {
    get {_storage._cdnSrcActive}
    set {_uniqueStorage()._cdnSrcActive = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_PbContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PbContent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}text\0\u{1}link\0\u{1}src\0\u{1}bsize\0\u{1}bigSrc\0\u{1}bigSize\0\u{1}cdnSrc\0\u{1}bigCdnSrc\0\u{1}imgType\0\u{1}c\0\u{1}voiceMD5\0\u{1}duringTime\0\u{2}\u{2}uid\0\u{1}dynamic\0\u{3}_static\0\u{1}width\0\u{1}height\0\u{2}\u{6}originSrc\0\u{2}\u{2}originSize\0\u{2}\u{4}mediaSubtitle\0\u{1}urlType\0\u{1}memeInfo\0\u{1}isLongPic\0\u{1}showOriginalBtn\0\u{1}cdnSrcActive\0")

  fileprivate class _StorageClass {
    var _type: Int32 = 0
    var _text: String = String()
    var _link: String = String()
    var _src: String = String()
    var _bsize: String = String()
    var _bigSrc: String = String()
    var _bigSize: String = String()
    var _cdnSrc: String = String()
    var _bigCdnSrc: String = String()
    var _imgType: String = String()
    var _c: String = String()
    var _voiceMd5: String = String()
    var _duringTime: UInt32 = 0
    var _uid: Int64 = 0
    var _dynamic: String = String()
    var _static: String = String()
    var _width: UInt32 = 0
    var _height: UInt32 = 0
    var _originSrc: String = String()
    var _originSize: UInt32 = 0
    var _mediaSubtitle: String = String()
    var _urlType: Int32 = 0
    var _memeInfo: Tieba_MemeInfo? = nil
    var _isLongPic: UInt32 = 0
    var _showOriginalBtn: UInt32 = 0
    var _cdnSrcActive: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _type = source._type
      _text = source._text
      _link = source._link
      _src = source._src
      _bsize = source._bsize
      _bigSrc = source._bigSrc
      _bigSize = source._bigSize
      _cdnSrc = source._cdnSrc
      _bigCdnSrc = source._bigCdnSrc
      _imgType = source._imgType
      _c = source._c
      _voiceMd5 = source._voiceMd5
      _duringTime = source._duringTime
      _uid = source._uid
      _dynamic = source._dynamic
      _static = source._static
      _width = source._width
      _height = source._height
      _originSrc = source._originSrc
      _originSize = source._originSize
      _mediaSubtitle = source._mediaSubtitle
      _urlType = source._urlType
      _memeInfo = source._memeInfo
      _isLongPic = source._isLongPic
      _showOriginalBtn = source._showOriginalBtn
      _cdnSrcActive = source._cdnSrcActive
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._type) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._text) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._link) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._src) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._bsize) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._bigSrc) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._bigSize) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._cdnSrc) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._bigCdnSrc) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._imgType) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._c) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._voiceMd5) }()
        case 13: try { try decoder.decodeSingularUInt32Field(value: &_storage._duringTime) }()
        case 15: try { try decoder.decodeSingularInt64Field(value: &_storage._uid) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._dynamic) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._static) }()
        case 18: try { try decoder.decodeSingularUInt32Field(value: &_storage._width) }()
        case 19: try { try decoder.decodeSingularUInt32Field(value: &_storage._height) }()
        case 25: try { try decoder.decodeSingularStringField(value: &_storage._originSrc) }()
        case 27: try { try decoder.decodeSingularUInt32Field(value: &_storage._originSize) }()
        case 31: try { try decoder.decodeSingularStringField(value: &_storage._mediaSubtitle) }()
        case 32: try { try decoder.decodeSingularInt32Field(value: &_storage._urlType) }()
        case 33: try { try decoder.decodeSingularMessageField(value: &_storage._memeInfo) }()
        case 34: try { try decoder.decodeSingularUInt32Field(value: &_storage._isLongPic) }()
        case 35: try { try decoder.decodeSingularUInt32Field(value: &_storage._showOriginalBtn) }()
        case 36: try { try decoder.decodeSingularStringField(value: &_storage._cdnSrcActive) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._type != 0 {
        try visitor.visitSingularInt32Field(value: _storage._type, fieldNumber: 1)
      }
      if !_storage._text.isEmpty {
        try visitor.visitSingularStringField(value: _storage._text, fieldNumber: 2)
      }
      if !_storage._link.isEmpty {
        try visitor.visitSingularStringField(value: _storage._link, fieldNumber: 3)
      }
      if !_storage._src.isEmpty {
        try visitor.visitSingularStringField(value: _storage._src, fieldNumber: 4)
      }
      if !_storage._bsize.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bsize, fieldNumber: 5)
      }
      if !_storage._bigSrc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bigSrc, fieldNumber: 6)
      }
      if !_storage._bigSize.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bigSize, fieldNumber: 7)
      }
      if !_storage._cdnSrc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cdnSrc, fieldNumber: 8)
      }
      if !_storage._bigCdnSrc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bigCdnSrc, fieldNumber: 9)
      }
      if !_storage._imgType.isEmpty {
        try visitor.visitSingularStringField(value: _storage._imgType, fieldNumber: 10)
      }
      if !_storage._c.isEmpty {
        try visitor.visitSingularStringField(value: _storage._c, fieldNumber: 11)
      }
      if !_storage._voiceMd5.isEmpty {
        try visitor.visitSingularStringField(value: _storage._voiceMd5, fieldNumber: 12)
      }
      if _storage._duringTime != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._duringTime, fieldNumber: 13)
      }
      if _storage._uid != 0 {
        try visitor.visitSingularInt64Field(value: _storage._uid, fieldNumber: 15)
      }
      if !_storage._dynamic.isEmpty {
        try visitor.visitSingularStringField(value: _storage._dynamic, fieldNumber: 16)
      }
      if !_storage._static.isEmpty {
        try visitor.visitSingularStringField(value: _storage._static, fieldNumber: 17)
      }
      if _storage._width != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._width, fieldNumber: 18)
      }
      if _storage._height != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._height, fieldNumber: 19)
      }
      if !_storage._originSrc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._originSrc, fieldNumber: 25)
      }
      if _storage._originSize != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._originSize, fieldNumber: 27)
      }
      if !_storage._mediaSubtitle.isEmpty {
        try visitor.visitSingularStringField(value: _storage._mediaSubtitle, fieldNumber: 31)
      }
      if _storage._urlType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._urlType, fieldNumber: 32)
      }
      try { if let v = _storage._memeInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 33)
      } }()
      if _storage._isLongPic != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._isLongPic, fieldNumber: 34)
      }
      if _storage._showOriginalBtn != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._showOriginalBtn, fieldNumber: 35)
      }
      if !_storage._cdnSrcActive.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cdnSrcActive, fieldNumber: 36)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PbContent, rhs: Tieba_PbContent) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._type != rhs_storage._type {return false}
        if _storage._text != rhs_storage._text {return false}
        if _storage._link != rhs_storage._link {return false}
        if _storage._src != rhs_storage._src {return false}
        if _storage._bsize != rhs_storage._bsize {return false}
        if _storage._bigSrc != rhs_storage._bigSrc {return false}
        if _storage._bigSize != rhs_storage._bigSize {return false}
        if _storage._cdnSrc != rhs_storage._cdnSrc {return false}
        if _storage._bigCdnSrc != rhs_storage._bigCdnSrc {return false}
        if _storage._imgType != rhs_storage._imgType {return false}
        if _storage._c != rhs_storage._c {return false}
        if _storage._voiceMd5 != rhs_storage._voiceMd5 {return false}
        if _storage._duringTime != rhs_storage._duringTime {return false}
        if _storage._uid != rhs_storage._uid {return false}
        if _storage._dynamic != rhs_storage._dynamic {return false}
        if _storage._static != rhs_storage._static {return false}
        if _storage._width != rhs_storage._width {return false}
        if _storage._height != rhs_storage._height {return false}
        if _storage._originSrc != rhs_storage._originSrc {return false}
        if _storage._originSize != rhs_storage._originSize {return false}
        if _storage._mediaSubtitle != rhs_storage._mediaSubtitle {return false}
        if _storage._urlType != rhs_storage._urlType {return false}
        if _storage._memeInfo != rhs_storage._memeInfo {return false}
        if _storage._isLongPic != rhs_storage._isLongPic {return false}
        if _storage._showOriginalBtn != rhs_storage._showOriginalBtn {return false}
        if _storage._cdnSrcActive != rhs_storage._cdnSrcActive {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
