// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PbPage/RecommendBook.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PbPage_RecommendBook: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var recommendText: String = String()

  var suggestText: String = String()

  var suggestURL: String = String()

  var bookID: String = String()

  var bookType: UInt32 = 0

  var bookCover: String = String()

  var bookTitle: String = String()

  var bookTips: [String] = []

  var bottonText: String = String()

  var subscriptIcon: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.pbPage"

nonisolated extension Tieba_PbPage_RecommendBook: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RecommendBook"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}recommend_text\0\u{3}suggest_text\0\u{3}suggest_url\0\u{3}book_id\0\u{3}book_type\0\u{3}book_cover\0\u{3}book_title\0\u{3}book_tips\0\u{3}botton_text\0\u{3}subscript_icon\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.recommendText) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.suggestText) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.suggestURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.bookID) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.bookType) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.bookCover) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.bookTitle) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.bookTips) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.bottonText) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.subscriptIcon) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.recommendText.isEmpty {
      try visitor.visitSingularStringField(value: self.recommendText, fieldNumber: 1)
    }
    if !self.suggestText.isEmpty {
      try visitor.visitSingularStringField(value: self.suggestText, fieldNumber: 2)
    }
    if !self.suggestURL.isEmpty {
      try visitor.visitSingularStringField(value: self.suggestURL, fieldNumber: 3)
    }
    if !self.bookID.isEmpty {
      try visitor.visitSingularStringField(value: self.bookID, fieldNumber: 4)
    }
    if self.bookType != 0 {
      try visitor.visitSingularUInt32Field(value: self.bookType, fieldNumber: 5)
    }
    if !self.bookCover.isEmpty {
      try visitor.visitSingularStringField(value: self.bookCover, fieldNumber: 6)
    }
    if !self.bookTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.bookTitle, fieldNumber: 7)
    }
    if !self.bookTips.isEmpty {
      try visitor.visitRepeatedStringField(value: self.bookTips, fieldNumber: 8)
    }
    if !self.bottonText.isEmpty {
      try visitor.visitSingularStringField(value: self.bottonText, fieldNumber: 9)
    }
    if !self.subscriptIcon.isEmpty {
      try visitor.visitSingularStringField(value: self.subscriptIcon, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PbPage_RecommendBook, rhs: Tieba_PbPage_RecommendBook) -> Bool {
    if lhs.recommendText != rhs.recommendText {return false}
    if lhs.suggestText != rhs.suggestText {return false}
    if lhs.suggestURL != rhs.suggestURL {return false}
    if lhs.bookID != rhs.bookID {return false}
    if lhs.bookType != rhs.bookType {return false}
    if lhs.bookCover != rhs.bookCover {return false}
    if lhs.bookTitle != rhs.bookTitle {return false}
    if lhs.bookTips != rhs.bookTips {return false}
    if lhs.bottonText != rhs.bottonText {return false}
    if lhs.subscriptIcon != rhs.subscriptIcon {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
