// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PbPage/GodCard.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PbPage_GodCard: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userName: String = String()

  var portrait: String = String()

  var timeEx: String = String()

  var text: String = String()

  var picURL: String = String()

  var buttonText: String = String()

  var buttonURL: String = String()

  var showFloor: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.pbPage"

nonisolated extension Tieba_PbPage_GodCard: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GodCard"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_name\0\u{1}portrait\0\u{3}time_ex\0\u{1}text\0\u{3}pic_url\0\u{3}button_text\0\u{3}button_url\0\u{3}show_floor\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.portrait) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.timeEx) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.picURL) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.buttonText) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.buttonURL) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.showFloor) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userName.isEmpty {
      try visitor.visitSingularStringField(value: self.userName, fieldNumber: 1)
    }
    if !self.portrait.isEmpty {
      try visitor.visitSingularStringField(value: self.portrait, fieldNumber: 2)
    }
    if !self.timeEx.isEmpty {
      try visitor.visitSingularStringField(value: self.timeEx, fieldNumber: 3)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 4)
    }
    if !self.picURL.isEmpty {
      try visitor.visitSingularStringField(value: self.picURL, fieldNumber: 5)
    }
    if !self.buttonText.isEmpty {
      try visitor.visitSingularStringField(value: self.buttonText, fieldNumber: 6)
    }
    if !self.buttonURL.isEmpty {
      try visitor.visitSingularStringField(value: self.buttonURL, fieldNumber: 7)
    }
    if self.showFloor != 0 {
      try visitor.visitSingularUInt32Field(value: self.showFloor, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PbPage_GodCard, rhs: Tieba_PbPage_GodCard) -> Bool {
    if lhs.userName != rhs.userName {return false}
    if lhs.portrait != rhs.portrait {return false}
    if lhs.timeEx != rhs.timeEx {return false}
    if lhs.text != rhs.text {return false}
    if lhs.picURL != rhs.picURL {return false}
    if lhs.buttonText != rhs.buttonText {return false}
    if lhs.buttonURL != rhs.buttonURL {return false}
    if lhs.showFloor != rhs.showFloor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
