// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PbPage/ForumHeadlineImgInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PbPage_ForumHeadlineImgInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var imgUserName: String = String()

  var imgURL: String = String()

  var rankNum: Int32 = 0

  var imgUserID: Int64 = 0

  var rankURL: String = String()

  var rankUpInfo: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.pbPage"

nonisolated extension Tieba_PbPage_ForumHeadlineImgInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ForumHeadlineImgInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}img_user_name\0\u{3}img_url\0\u{3}rank_num\0\u{3}img_user_id\0\u{3}rank_url\0\u{3}rank_up_info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.imgUserName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.imgURL) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.rankNum) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.imgUserID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.rankURL) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.rankUpInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.imgUserName.isEmpty {
      try visitor.visitSingularStringField(value: self.imgUserName, fieldNumber: 1)
    }
    if !self.imgURL.isEmpty {
      try visitor.visitSingularStringField(value: self.imgURL, fieldNumber: 2)
    }
    if self.rankNum != 0 {
      try visitor.visitSingularInt32Field(value: self.rankNum, fieldNumber: 3)
    }
    if self.imgUserID != 0 {
      try visitor.visitSingularInt64Field(value: self.imgUserID, fieldNumber: 4)
    }
    if !self.rankURL.isEmpty {
      try visitor.visitSingularStringField(value: self.rankURL, fieldNumber: 5)
    }
    if !self.rankUpInfo.isEmpty {
      try visitor.visitSingularStringField(value: self.rankUpInfo, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PbPage_ForumHeadlineImgInfo, rhs: Tieba_PbPage_ForumHeadlineImgInfo) -> Bool {
    if lhs.imgUserName != rhs.imgUserName {return false}
    if lhs.imgURL != rhs.imgURL {return false}
    if lhs.rankNum != rhs.rankNum {return false}
    if lhs.imgUserID != rhs.imgUserID {return false}
    if lhs.rankURL != rhs.rankURL {return false}
    if lhs.rankUpInfo != rhs.rankUpInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
