// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PbPresentList.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PbPresentList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var giftID: UInt32 = 0

  var giftName: String = String()

  var thumbnailURL: String = String()

  var num: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_PbPresentList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PbPresentList"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}gift_id\0\u{3}gift_name\0\u{3}thumbnail_url\0\u{1}num\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.giftID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.giftName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.thumbnailURL) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.num) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.giftID != 0 {
      try visitor.visitSingularUInt32Field(value: self.giftID, fieldNumber: 1)
    }
    if !self.giftName.isEmpty {
      try visitor.visitSingularStringField(value: self.giftName, fieldNumber: 2)
    }
    if !self.thumbnailURL.isEmpty {
      try visitor.visitSingularStringField(value: self.thumbnailURL, fieldNumber: 3)
    }
    if self.num != 0 {
      try visitor.visitSingularUInt32Field(value: self.num, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PbPresentList, rhs: Tieba_PbPresentList) -> Bool {
    if lhs.giftID != rhs.giftID {return false}
    if lhs.giftName != rhs.giftName {return false}
    if lhs.thumbnailURL != rhs.thumbnailURL {return false}
    if lhs.num != rhs.num {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
