// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PbTopAgreePost.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PbTopAgreePost: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var postList: [Tieba_Post] = []

  var postIDList: [Int64] = []

  var forumTopList: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_PbTopAgreePost: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PbTopAgreePost"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}post_list\0\u{4}\u{2}post_id_list\0\u{3}forum_top_list\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.postList) }()
      case 3: try { try decoder.decodeRepeatedInt64Field(value: &self.postIDList) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.forumTopList) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.postList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.postList, fieldNumber: 1)
    }
    if !self.postIDList.isEmpty {
      try visitor.visitPackedInt64Field(value: self.postIDList, fieldNumber: 3)
    }
    if !self.forumTopList.isEmpty {
      try visitor.visitSingularStringField(value: self.forumTopList, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PbTopAgreePost, rhs: Tieba_PbTopAgreePost) -> Bool {
    if lhs.postList != rhs.postList {return false}
    if lhs.postIDList != rhs.postIDList {return false}
    if lhs.forumTopList != rhs.forumTopList {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
