// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PollInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PollInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Int32 = 0

  var isMulti: Int32 = 0

  var totalNum: Int64 = 0

  var optionsCount: Int32 = 0

  var isPolled: Int32 = 0

  var polledValue: String = String()

  var tips: String = String()

  var endTime: Int32 = 0

  var options: [Tieba_PollOption] = []

  var status: Int32 = 0

  var totalPoll: Int64 = 0

  var title: String = String()

  var lastTime: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_PollInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PollInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{3}is_multi\0\u{3}total_num\0\u{3}options_count\0\u{3}is_polled\0\u{3}polled_value\0\u{1}tips\0\u{3}end_time\0\u{1}options\0\u{1}status\0\u{3}total_poll\0\u{1}title\0\u{3}last_time\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.type) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.isMulti) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.totalNum) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.optionsCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.isPolled) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.polledValue) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.tips) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.endTime) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.options) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.status) }()
      case 11: try { try decoder.decodeSingularInt64Field(value: &self.totalPoll) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 13: try { try decoder.decodeSingularUInt32Field(value: &self.lastTime) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != 0 {
      try visitor.visitSingularInt32Field(value: self.type, fieldNumber: 1)
    }
    if self.isMulti != 0 {
      try visitor.visitSingularInt32Field(value: self.isMulti, fieldNumber: 2)
    }
    if self.totalNum != 0 {
      try visitor.visitSingularInt64Field(value: self.totalNum, fieldNumber: 3)
    }
    if self.optionsCount != 0 {
      try visitor.visitSingularInt32Field(value: self.optionsCount, fieldNumber: 4)
    }
    if self.isPolled != 0 {
      try visitor.visitSingularInt32Field(value: self.isPolled, fieldNumber: 5)
    }
    if !self.polledValue.isEmpty {
      try visitor.visitSingularStringField(value: self.polledValue, fieldNumber: 6)
    }
    if !self.tips.isEmpty {
      try visitor.visitSingularStringField(value: self.tips, fieldNumber: 7)
    }
    if self.endTime != 0 {
      try visitor.visitSingularInt32Field(value: self.endTime, fieldNumber: 8)
    }
    if !self.options.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.options, fieldNumber: 9)
    }
    if self.status != 0 {
      try visitor.visitSingularInt32Field(value: self.status, fieldNumber: 10)
    }
    if self.totalPoll != 0 {
      try visitor.visitSingularInt64Field(value: self.totalPoll, fieldNumber: 11)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 12)
    }
    if self.lastTime != 0 {
      try visitor.visitSingularUInt32Field(value: self.lastTime, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PollInfo, rhs: Tieba_PollInfo) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.isMulti != rhs.isMulti {return false}
    if lhs.totalNum != rhs.totalNum {return false}
    if lhs.optionsCount != rhs.optionsCount {return false}
    if lhs.isPolled != rhs.isPolled {return false}
    if lhs.polledValue != rhs.polledValue {return false}
    if lhs.tips != rhs.tips {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.options != rhs.options {return false}
    if lhs.status != rhs.status {return false}
    if lhs.totalPoll != rhs.totalPoll {return false}
    if lhs.title != rhs.title {return false}
    if lhs.lastTime != rhs.lastTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
