// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Position.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Position: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var frs: Int32 = 0

  var pb: Int32 = 0

  var home: Int32 = 0

  var card: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_Position: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Position"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}frs\0\u{1}pb\0\u{1}home\0\u{1}card\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.frs) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.pb) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.home) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.card) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.frs != 0 {
      try visitor.visitSingularInt32Field(value: self.frs, fieldNumber: 1)
    }
    if self.pb != 0 {
      try visitor.visitSingularInt32Field(value: self.pb, fieldNumber: 2)
    }
    if self.home != 0 {
      try visitor.visitSingularInt32Field(value: self.home, fieldNumber: 3)
    }
    if self.card != 0 {
      try visitor.visitSingularInt32Field(value: self.card, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Position, rhs: Tieba_Position) -> Bool {
    if lhs.frs != rhs.frs {return false}
    if lhs.pb != rhs.pb {return false}
    if lhs.home != rhs.home {return false}
    if lhs.card != rhs.card {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
