// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PrivSets.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_PrivSets: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var like: Int32 = 0

  var group: Int32 = 0

  var post: Int32 = 0

  var live: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_PrivSets: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PrivSets"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}like\0\u{1}group\0\u{1}post\0\u{2}\u{2}live\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.like) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.group) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.post) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.live) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.like != 0 {
      try visitor.visitSingularInt32Field(value: self.like, fieldNumber: 2)
    }
    if self.group != 0 {
      try visitor.visitSingularInt32Field(value: self.group, fieldNumber: 3)
    }
    if self.post != 0 {
      try visitor.visitSingularInt32Field(value: self.post, fieldNumber: 4)
    }
    if self.live != 0 {
      try visitor.visitSingularInt32Field(value: self.live, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_PrivSets, rhs: Tieba_PrivSets) -> Bool {
    if lhs.like != rhs.like {return false}
    if lhs.group != rhs.group {return false}
    if lhs.post != rhs.post {return false}
    if lhs.live != rhs.live {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
