// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Profile/ProfileRequestData.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Profile_ProfileRequestData: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var uid: Int64 {
    get {_storage._uid ?? 0}
    set {_uniqueStorage()._uid = newValue}
  }
  /// Returns true if `uid` has been explicitly set.
  var hasUid: Bool {_storage._uid != nil}
  /// Clears the value of `uid`. Subsequent reads from it will return its default value.
  mutating func clearUid() {_uniqueStorage()._uid = nil}

  var needPostCount: UInt32 {
    get {_storage._needPostCount}
    set {_uniqueStorage()._needPostCount = newValue}
  }

  var friendUid: Int64 {
    get {_storage._friendUid ?? 0}
    set {_uniqueStorage()._friendUid = newValue}
  }
  /// Returns true if `friendUid` has been explicitly set.
  var hasFriendUid: Bool {_storage._friendUid != nil}
  /// Clears the value of `friendUid`. Subsequent reads from it will return its default value.
  mutating func clearFriendUid() {_uniqueStorage()._friendUid = nil}

  var isGuest: UInt32 {
    get {_storage._isGuest}
    set {_uniqueStorage()._isGuest = newValue}
  }

  var stType: String {
    get {_storage._stType}
    set {_uniqueStorage()._stType = newValue}
  }

  var pn: UInt32 {
    get {_storage._pn}
    set {_uniqueStorage()._pn = newValue}
  }

  var rn: UInt32 {
    get {_storage._rn}
    set {_uniqueStorage()._rn = newValue}
  }

  var hasPlist_p: UInt32 {
    get {_storage._hasPlist_p}
    set {_uniqueStorage()._hasPlist_p = newValue}
  }

  var common: Tieba_CommonRequest {
    get {_storage._common ?? Tieba_CommonRequest()}
    set {_uniqueStorage()._common = newValue}
  }
  /// Returns true if `common` has been explicitly set.
  var hasCommon: Bool {_storage._common != nil}
  /// Clears the value of `common`. Subsequent reads from it will return its default value.
  mutating func clearCommon() {_uniqueStorage()._common = nil}

  var scrW: UInt32 {
    get {_storage._scrW}
    set {_uniqueStorage()._scrW = newValue}
  }

  var scrH: UInt32 {
    get {_storage._scrH}
    set {_uniqueStorage()._scrH = newValue}
  }

  var qType: UInt32 {
    get {_storage._qType}
    set {_uniqueStorage()._qType = newValue}
  }

  var scrDip: Double {
    get {_storage._scrDip}
    set {_uniqueStorage()._scrDip = newValue}
  }

  var isFromUsercenter: Int32 {
    get {_storage._isFromUsercenter}
    set {_uniqueStorage()._isFromUsercenter = newValue}
  }

  var page: Int32 {
    get {_storage._page}
    set {_uniqueStorage()._page = newValue}
  }

  var friendUidPortrait: String {
    get {_storage._friendUidPortrait}
    set {_uniqueStorage()._friendUidPortrait = newValue}
  }

  var historyForumIds: String {
    get {_storage._historyForumIds}
    set {_uniqueStorage()._historyForumIds = newValue}
  }

  var historyForumNames: String {
    get {_storage._historyForumNames}
    set {_uniqueStorage()._historyForumNames = newValue}
  }

  var needUsergrowthTask: Int32 {
    get {_storage._needUsergrowthTask}
    set {_uniqueStorage()._needUsergrowthTask = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.profile"

nonisolated extension Tieba_Profile_ProfileRequestData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProfileRequestData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uid\0\u{3}need_post_count\0\u{3}friend_uid\0\u{3}is_guest\0\u{3}st_type\0\u{1}pn\0\u{1}rn\0\u{3}has_plist\0\u{1}common\0\u{3}scr_w\0\u{3}scr_h\0\u{3}q_type\0\u{3}scr_dip\0\u{3}is_from_usercenter\0\u{1}page\0\u{3}friend_uid_portrait\0\u{3}history_forum_ids\0\u{3}history_forum_names\0\u{3}need_usergrowth_task\0")

  fileprivate class _StorageClass {
    var _uid: Int64? = nil
    var _needPostCount: UInt32 = 0
    var _friendUid: Int64? = nil
    var _isGuest: UInt32 = 0
    var _stType: String = String()
    var _pn: UInt32 = 0
    var _rn: UInt32 = 0
    var _hasPlist_p: UInt32 = 0
    var _common: Tieba_CommonRequest? = nil
    var _scrW: UInt32 = 0
    var _scrH: UInt32 = 0
    var _qType: UInt32 = 0
    var _scrDip: Double = 0
    var _isFromUsercenter: Int32 = 0
    var _page: Int32 = 0
    var _friendUidPortrait: String = String()
    var _historyForumIds: String = String()
    var _historyForumNames: String = String()
    var _needUsergrowthTask: Int32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _uid = source._uid
      _needPostCount = source._needPostCount
      _friendUid = source._friendUid
      _isGuest = source._isGuest
      _stType = source._stType
      _pn = source._pn
      _rn = source._rn
      _hasPlist_p = source._hasPlist_p
      _common = source._common
      _scrW = source._scrW
      _scrH = source._scrH
      _qType = source._qType
      _scrDip = source._scrDip
      _isFromUsercenter = source._isFromUsercenter
      _page = source._page
      _friendUidPortrait = source._friendUidPortrait
      _historyForumIds = source._historyForumIds
      _historyForumNames = source._historyForumNames
      _needUsergrowthTask = source._needUsergrowthTask
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt64Field(value: &_storage._uid) }()
        case 2: try { try decoder.decodeSingularUInt32Field(value: &_storage._needPostCount) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._friendUid) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._isGuest) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._stType) }()
        case 6: try { try decoder.decodeSingularUInt32Field(value: &_storage._pn) }()
        case 7: try { try decoder.decodeSingularUInt32Field(value: &_storage._rn) }()
        case 8: try { try decoder.decodeSingularUInt32Field(value: &_storage._hasPlist_p) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._common) }()
        case 10: try { try decoder.decodeSingularUInt32Field(value: &_storage._scrW) }()
        case 11: try { try decoder.decodeSingularUInt32Field(value: &_storage._scrH) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._qType) }()
        case 13: try { try decoder.decodeSingularDoubleField(value: &_storage._scrDip) }()
        case 14: try { try decoder.decodeSingularInt32Field(value: &_storage._isFromUsercenter) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._page) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._friendUidPortrait) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._historyForumIds) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._historyForumNames) }()
        case 19: try { try decoder.decodeSingularInt32Field(value: &_storage._needUsergrowthTask) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._uid {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 1)
      } }()
      if _storage._needPostCount != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._needPostCount, fieldNumber: 2)
      }
      try { if let v = _storage._friendUid {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
      } }()
      if _storage._isGuest != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._isGuest, fieldNumber: 4)
      }
      if !_storage._stType.isEmpty {
        try visitor.visitSingularStringField(value: _storage._stType, fieldNumber: 5)
      }
      if _storage._pn != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._pn, fieldNumber: 6)
      }
      if _storage._rn != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._rn, fieldNumber: 7)
      }
      if _storage._hasPlist_p != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._hasPlist_p, fieldNumber: 8)
      }
      try { if let v = _storage._common {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if _storage._scrW != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._scrW, fieldNumber: 10)
      }
      if _storage._scrH != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._scrH, fieldNumber: 11)
      }
      if _storage._qType != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._qType, fieldNumber: 12)
      }
      if _storage._scrDip.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._scrDip, fieldNumber: 13)
      }
      if _storage._isFromUsercenter != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isFromUsercenter, fieldNumber: 14)
      }
      if _storage._page != 0 {
        try visitor.visitSingularInt32Field(value: _storage._page, fieldNumber: 15)
      }
      if !_storage._friendUidPortrait.isEmpty {
        try visitor.visitSingularStringField(value: _storage._friendUidPortrait, fieldNumber: 16)
      }
      if !_storage._historyForumIds.isEmpty {
        try visitor.visitSingularStringField(value: _storage._historyForumIds, fieldNumber: 17)
      }
      if !_storage._historyForumNames.isEmpty {
        try visitor.visitSingularStringField(value: _storage._historyForumNames, fieldNumber: 18)
      }
      if _storage._needUsergrowthTask != 0 {
        try visitor.visitSingularInt32Field(value: _storage._needUsergrowthTask, fieldNumber: 19)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Profile_ProfileRequestData, rhs: Tieba_Profile_ProfileRequestData) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._uid != rhs_storage._uid {return false}
        if _storage._needPostCount != rhs_storage._needPostCount {return false}
        if _storage._friendUid != rhs_storage._friendUid {return false}
        if _storage._isGuest != rhs_storage._isGuest {return false}
        if _storage._stType != rhs_storage._stType {return false}
        if _storage._pn != rhs_storage._pn {return false}
        if _storage._rn != rhs_storage._rn {return false}
        if _storage._hasPlist_p != rhs_storage._hasPlist_p {return false}
        if _storage._common != rhs_storage._common {return false}
        if _storage._scrW != rhs_storage._scrW {return false}
        if _storage._scrH != rhs_storage._scrH {return false}
        if _storage._qType != rhs_storage._qType {return false}
        if _storage._scrDip != rhs_storage._scrDip {return false}
        if _storage._isFromUsercenter != rhs_storage._isFromUsercenter {return false}
        if _storage._page != rhs_storage._page {return false}
        if _storage._friendUidPortrait != rhs_storage._friendUidPortrait {return false}
        if _storage._historyForumIds != rhs_storage._historyForumIds {return false}
        if _storage._historyForumNames != rhs_storage._historyForumNames {return false}
        if _storage._needUsergrowthTask != rhs_storage._needUsergrowthTask {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
