// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Profile/FinanceTabItems.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Profile_FinanceTabItems: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var tabName: String = String()

  var tabURL: String = String()

  var iconURL: String = String()

  var descText: String = String()

  var tabBubble: String = String()

  var tabType: String = String()

  var statistic: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.profile"

nonisolated extension Tieba_Profile_FinanceTabItems: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FinanceTabItems"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}tab_name\0\u{3}tab_url\0\u{3}icon_url\0\u{3}desc_text\0\u{3}tab_bubble\0\u{3}tab_type\0\u{1}statistic\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tabName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.tabURL) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.iconURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.descText) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.tabBubble) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.tabType) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.statistic) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.tabName.isEmpty {
      try visitor.visitSingularStringField(value: self.tabName, fieldNumber: 1)
    }
    if !self.tabURL.isEmpty {
      try visitor.visitSingularStringField(value: self.tabURL, fieldNumber: 2)
    }
    if !self.iconURL.isEmpty {
      try visitor.visitSingularStringField(value: self.iconURL, fieldNumber: 3)
    }
    if !self.descText.isEmpty {
      try visitor.visitSingularStringField(value: self.descText, fieldNumber: 4)
    }
    if !self.tabBubble.isEmpty {
      try visitor.visitSingularStringField(value: self.tabBubble, fieldNumber: 5)
    }
    if !self.tabType.isEmpty {
      try visitor.visitSingularStringField(value: self.tabType, fieldNumber: 6)
    }
    if !self.statistic.isEmpty {
      try visitor.visitSingularStringField(value: self.statistic, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Profile_FinanceTabItems, rhs: Tieba_Profile_FinanceTabItems) -> Bool {
    if lhs.tabName != rhs.tabName {return false}
    if lhs.tabURL != rhs.tabURL {return false}
    if lhs.iconURL != rhs.iconURL {return false}
    if lhs.descText != rhs.descText {return false}
    if lhs.tabBubble != rhs.tabBubble {return false}
    if lhs.tabType != rhs.tabType {return false}
    if lhs.statistic != rhs.statistic {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
