// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Profile/ForumGodDetailInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Profile_ForumGodDetailInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var godID: Int64 = 0

  var userID: Int64 = 0

  var intro: String = String()

  var detailIntro: String = String()

  var forumID: Int64 = 0

  var forumName: String = String()

  var avatar: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.profile"

nonisolated extension Tieba_Profile_ForumGodDetailInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ForumGodDetailInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}god_id\0\u{3}user_id\0\u{1}intro\0\u{3}detail_intro\0\u{3}forum_id\0\u{3}forum_name\0\u{1}avatar\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.godID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.userID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.intro) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.detailIntro) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.forumID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.forumName) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.avatar) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.godID != 0 {
      try visitor.visitSingularInt64Field(value: self.godID, fieldNumber: 1)
    }
    if self.userID != 0 {
      try visitor.visitSingularInt64Field(value: self.userID, fieldNumber: 2)
    }
    if !self.intro.isEmpty {
      try visitor.visitSingularStringField(value: self.intro, fieldNumber: 3)
    }
    if !self.detailIntro.isEmpty {
      try visitor.visitSingularStringField(value: self.detailIntro, fieldNumber: 4)
    }
    if self.forumID != 0 {
      try visitor.visitSingularInt64Field(value: self.forumID, fieldNumber: 5)
    }
    if !self.forumName.isEmpty {
      try visitor.visitSingularStringField(value: self.forumName, fieldNumber: 6)
    }
    if !self.avatar.isEmpty {
      try visitor.visitSingularStringField(value: self.avatar, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Profile_ForumGodDetailInfo, rhs: Tieba_Profile_ForumGodDetailInfo) -> Bool {
    if lhs.godID != rhs.godID {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.intro != rhs.intro {return false}
    if lhs.detailIntro != rhs.detailIntro {return false}
    if lhs.forumID != rhs.forumID {return false}
    if lhs.forumName != rhs.forumName {return false}
    if lhs.avatar != rhs.avatar {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
