// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Profile/UserAgreeInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Profile_UserAgreeInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var totalAgreeNum: Int64 = 0

  var normalAgreeNum: Int64 = 0

  var userAgreeNum: Int64 = 0

  var videoAgreeNum: Int64 = 0

  var alaAgreeNum: Int64 = 0

  var hasUserAgree_p: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.profile"

nonisolated extension Tieba_Profile_UserAgreeInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserAgreeInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}total_agree_num\0\u{3}normal_agree_num\0\u{3}user_agree_num\0\u{3}video_agree_num\0\u{3}ala_agree_num\0\u{3}has_user_agree\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.totalAgreeNum) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.normalAgreeNum) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.userAgreeNum) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.videoAgreeNum) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.alaAgreeNum) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.hasUserAgree_p) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.totalAgreeNum != 0 {
      try visitor.visitSingularInt64Field(value: self.totalAgreeNum, fieldNumber: 1)
    }
    if self.normalAgreeNum != 0 {
      try visitor.visitSingularInt64Field(value: self.normalAgreeNum, fieldNumber: 2)
    }
    if self.userAgreeNum != 0 {
      try visitor.visitSingularInt64Field(value: self.userAgreeNum, fieldNumber: 3)
    }
    if self.videoAgreeNum != 0 {
      try visitor.visitSingularInt64Field(value: self.videoAgreeNum, fieldNumber: 4)
    }
    if self.alaAgreeNum != 0 {
      try visitor.visitSingularInt64Field(value: self.alaAgreeNum, fieldNumber: 5)
    }
    if self.hasUserAgree_p != 0 {
      try visitor.visitSingularInt32Field(value: self.hasUserAgree_p, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Profile_UserAgreeInfo, rhs: Tieba_Profile_UserAgreeInfo) -> Bool {
    if lhs.totalAgreeNum != rhs.totalAgreeNum {return false}
    if lhs.normalAgreeNum != rhs.normalAgreeNum {return false}
    if lhs.userAgreeNum != rhs.userAgreeNum {return false}
    if lhs.videoAgreeNum != rhs.videoAgreeNum {return false}
    if lhs.alaAgreeNum != rhs.alaAgreeNum {return false}
    if lhs.hasUserAgree_p != rhs.hasUserAgree_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
