// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RecommendTopicList.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_RecommendTopicList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var topicID: UInt64 = 0

  var topicName: String = String()

  var type: UInt32 = 0

  var discussNum: UInt64 = 0

  var tag: UInt32 = 0

  var topicDesc: String = String()

  var topicPic: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_RecommendTopicList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RecommendTopicList"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}topicId\0\u{1}topicName\0\u{1}type\0\u{1}discussNum\0\u{1}tag\0\u{1}topicDesc\0\u{1}topicPic\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.topicID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.topicName) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.type) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.discussNum) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.tag) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.topicDesc) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.topicPic) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.topicID != 0 {
      try visitor.visitSingularUInt64Field(value: self.topicID, fieldNumber: 1)
    }
    if !self.topicName.isEmpty {
      try visitor.visitSingularStringField(value: self.topicName, fieldNumber: 2)
    }
    if self.type != 0 {
      try visitor.visitSingularUInt32Field(value: self.type, fieldNumber: 3)
    }
    if self.discussNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.discussNum, fieldNumber: 4)
    }
    if self.tag != 0 {
      try visitor.visitSingularUInt32Field(value: self.tag, fieldNumber: 5)
    }
    if !self.topicDesc.isEmpty {
      try visitor.visitSingularStringField(value: self.topicDesc, fieldNumber: 6)
    }
    if !self.topicPic.isEmpty {
      try visitor.visitSingularStringField(value: self.topicPic, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_RecommendTopicList, rhs: Tieba_RecommendTopicList) -> Bool {
    if lhs.topicID != rhs.topicID {return false}
    if lhs.topicName != rhs.topicName {return false}
    if lhs.type != rhs.type {return false}
    if lhs.discussNum != rhs.discussNum {return false}
    if lhs.tag != rhs.tag {return false}
    if lhs.topicDesc != rhs.topicDesc {return false}
    if lhs.topicPic != rhs.topicPic {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
