// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SearchSug/SearchSugResponseData.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_SearchSug_SearchSugResponseData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var forumLoc: Int32 = 0

  var list: [String] = []

  var forumList: [Tieba_ForumInfo] = []

  var forumCard: Tieba_RecommendForumInfo {
    get {_forumCard ?? Tieba_RecommendForumInfo()}
    set {_forumCard = newValue}
  }
  /// Returns true if `forumCard` has been explicitly set.
  var hasForumCard: Bool {self._forumCard != nil}
  /// Clears the value of `forumCard`. Subsequent reads from it will return its default value.
  mutating func clearForumCard() {self._forumCard = nil}

  var itemCard: Tieba_Item {
    get {_itemCard ?? Tieba_Item()}
    set {_itemCard = newValue}
  }
  /// Returns true if `itemCard` has been explicitly set.
  var hasItemCard: Bool {self._itemCard != nil}
  /// Clears the value of `itemCard`. Subsequent reads from it will return its default value.
  mutating func clearItemCard() {self._itemCard = nil}

  var liveCard: [Tieba_SugLiveInfo] = []

  var rankingCard: Tieba_SugRankingInfo {
    get {_rankingCard ?? Tieba_SugRankingInfo()}
    set {_rankingCard = newValue}
  }
  /// Returns true if `rankingCard` has been explicitly set.
  var hasRankingCard: Bool {self._rankingCard != nil}
  /// Clears the value of `rankingCard`. Subsequent reads from it will return its default value.
  mutating func clearRankingCard() {self._rankingCard = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _forumCard: Tieba_RecommendForumInfo? = nil
  fileprivate var _itemCard: Tieba_Item? = nil
  fileprivate var _rankingCard: Tieba_SugRankingInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.searchSug"

nonisolated extension Tieba_SearchSug_SearchSugResponseData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SearchSugResponseData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}forum_loc\0\u{1}list\0\u{3}forum_list\0\u{3}forum_card\0\u{3}item_card\0\u{3}live_card\0\u{3}ranking_card\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.forumLoc) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.list) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.forumList) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._forumCard) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._itemCard) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.liveCard) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._rankingCard) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.forumLoc != 0 {
      try visitor.visitSingularInt32Field(value: self.forumLoc, fieldNumber: 1)
    }
    if !self.list.isEmpty {
      try visitor.visitRepeatedStringField(value: self.list, fieldNumber: 2)
    }
    if !self.forumList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.forumList, fieldNumber: 3)
    }
    try { if let v = self._forumCard {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._itemCard {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.liveCard.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.liveCard, fieldNumber: 6)
    }
    try { if let v = self._rankingCard {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_SearchSug_SearchSugResponseData, rhs: Tieba_SearchSug_SearchSugResponseData) -> Bool {
    if lhs.forumLoc != rhs.forumLoc {return false}
    if lhs.list != rhs.list {return false}
    if lhs.forumList != rhs.forumList {return false}
    if lhs._forumCard != rhs._forumCard {return false}
    if lhs._itemCard != rhs._itemCard {return false}
    if lhs.liveCard != rhs.liveCard {return false}
    if lhs._rankingCard != rhs._rankingCard {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
