// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SimpleThreadInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_SimpleThreadInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var tid: UInt64 = 0

  var title: String = String()

  var replyNum: Int32 = 0

  var lastTimeInt: Int32 = 0

  var abstract: [Tieba_Abstract] = []

  var zan: Tieba_Zan {
    get {_zan ?? Tieba_Zan()}
    set {_zan = newValue}
  }
  /// Returns true if `zan` has been explicitly set.
  var hasZan: Bool {self._zan != nil}
  /// Clears the value of `zan`. Subsequent reads from it will return its default value.
  mutating func clearZan() {self._zan = nil}

  var threadType: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _zan: Tieba_Zan? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_SimpleThreadInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SimpleThreadInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}tid\0\u{1}title\0\u{3}reply_num\0\u{3}last_time_int\0\u{3}_abstract\0\u{1}zan\0\u{3}thread_type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.tid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.replyNum) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.lastTimeInt) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.abstract) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._zan) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.threadType) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.tid != 0 {
      try visitor.visitSingularUInt64Field(value: self.tid, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if self.replyNum != 0 {
      try visitor.visitSingularInt32Field(value: self.replyNum, fieldNumber: 3)
    }
    if self.lastTimeInt != 0 {
      try visitor.visitSingularInt32Field(value: self.lastTimeInt, fieldNumber: 4)
    }
    if !self.abstract.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.abstract, fieldNumber: 5)
    }
    try { if let v = self._zan {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if self.threadType != 0 {
      try visitor.visitSingularUInt64Field(value: self.threadType, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_SimpleThreadInfo, rhs: Tieba_SimpleThreadInfo) -> Bool {
    if lhs.tid != rhs.tid {return false}
    if lhs.title != rhs.title {return false}
    if lhs.replyNum != rhs.replyNum {return false}
    if lhs.lastTimeInt != rhs.lastTimeInt {return false}
    if lhs.abstract != rhs.abstract {return false}
    if lhs._zan != rhs._zan {return false}
    if lhs.threadType != rhs.threadType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
