// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Terminal.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_Terminal: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pc: Int32 = 0

  var wap: Int32 = 0

  var client: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_Terminal: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Terminal"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pc\0\u{1}wap\0\u{1}client\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.pc) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.wap) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.client) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pc != 0 {
      try visitor.visitSingularInt32Field(value: self.pc, fieldNumber: 1)
    }
    if self.wap != 0 {
      try visitor.visitSingularInt32Field(value: self.wap, fieldNumber: 2)
    }
    if self.client != 0 {
      try visitor.visitSingularInt32Field(value: self.client, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_Terminal, rhs: Tieba_Terminal) -> Bool {
    if lhs.pc != rhs.pc {return false}
    if lhs.wap != rhs.wap {return false}
    if lhs.client != rhs.client {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
