// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ThreadModule.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_ThreadModule: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var moduleID: Int64 = 0

  var moduleName: String = String()

  var threadInfo: [Tieba_ThreadInfo] = []

  var showNum: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_ThreadModule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ThreadModule"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}module_id\0\u{3}module_name\0\u{3}thread_info\0\u{3}show_num\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.moduleID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.moduleName) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.threadInfo) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.showNum) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.moduleID != 0 {
      try visitor.visitSingularInt64Field(value: self.moduleID, fieldNumber: 1)
    }
    if !self.moduleName.isEmpty {
      try visitor.visitSingularStringField(value: self.moduleName, fieldNumber: 2)
    }
    if !self.threadInfo.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.threadInfo, fieldNumber: 3)
    }
    if self.showNum != 0 {
      try visitor.visitSingularInt64Field(value: self.showNum, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_ThreadModule, rhs: Tieba_ThreadModule) -> Bool {
    if lhs.moduleID != rhs.moduleID {return false}
    if lhs.moduleName != rhs.moduleName {return false}
    if lhs.threadInfo != rhs.threadInfo {return false}
    if lhs.showNum != rhs.showNum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
