// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: TPointPost.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_TPointPost: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var isTuiguang: UInt32 {
    get {_storage._isTuiguang}
    set {_uniqueStorage()._isTuiguang = newValue}
  }

  var position: String {
    get {_storage._position}
    set {_uniqueStorage()._position = newValue}
  }

  var templateID: Int64 {
    get {_storage._templateID}
    set {_uniqueStorage()._templateID = newValue}
  }

  var templateType: Int32 {
    get {_storage._templateType}
    set {_uniqueStorage()._templateType = newValue}
  }

  var actBtn: [Tieba_ActBtn] {
    get {_storage._actBtn}
    set {_uniqueStorage()._actBtn = newValue}
  }

  var tImgs: [Tieba_Timgs] {
    get {_storage._tImgs}
    set {_uniqueStorage()._tImgs = newValue}
  }

  var detailInfo: Tieba_DetailInfo {
    get {_storage._detailInfo ?? Tieba_DetailInfo()}
    set {_uniqueStorage()._detailInfo = newValue}
  }
  /// Returns true if `detailInfo` has been explicitly set.
  var hasDetailInfo: Bool {_storage._detailInfo != nil}
  /// Clears the value of `detailInfo`. Subsequent reads from it will return its default value.
  mutating func clearDetailInfo() {_uniqueStorage()._detailInfo = nil}

  var monitorID: String {
    get {_storage._monitorID}
    set {_uniqueStorage()._monitorID = newValue}
  }

  var hiddenDay: Int32 {
    get {_storage._hiddenDay}
    set {_uniqueStorage()._hiddenDay = newValue}
  }

  var tVideo: Tieba_VideoInfo {
    get {_storage._tVideo ?? Tieba_VideoInfo()}
    set {_uniqueStorage()._tVideo = newValue}
  }
  /// Returns true if `tVideo` has been explicitly set.
  var hasTVideo: Bool {_storage._tVideo != nil}
  /// Clears the value of `tVideo`. Subsequent reads from it will return its default value.
  mutating func clearTVideo() {_uniqueStorage()._tVideo = nil}

  var tagName: String {
    get {_storage._tagName}
    set {_uniqueStorage()._tagName = newValue}
  }

  var tagNameURL: String {
    get {_storage._tagNameURL}
    set {_uniqueStorage()._tagNameURL = newValue}
  }

  var tagNameWh: String {
    get {_storage._tagNameWh}
    set {_uniqueStorage()._tagNameWh = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_TPointPost: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TPointPost"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_tuiguang\0\u{1}position\0\u{3}template_id\0\u{3}template_type\0\u{3}act_btn\0\u{3}t_imgs\0\u{3}detail_info\0\u{3}monitor_id\0\u{3}hidden_day\0\u{3}t_video\0\u{3}tag_name\0\u{3}tag_name_url\0\u{3}tag_name_wh\0")

  fileprivate class _StorageClass {
    var _isTuiguang: UInt32 = 0
    var _position: String = String()
    var _templateID: Int64 = 0
    var _templateType: Int32 = 0
    var _actBtn: [Tieba_ActBtn] = []
    var _tImgs: [Tieba_Timgs] = []
    var _detailInfo: Tieba_DetailInfo? = nil
    var _monitorID: String = String()
    var _hiddenDay: Int32 = 0
    var _tVideo: Tieba_VideoInfo? = nil
    var _tagName: String = String()
    var _tagNameURL: String = String()
    var _tagNameWh: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _isTuiguang = source._isTuiguang
      _position = source._position
      _templateID = source._templateID
      _templateType = source._templateType
      _actBtn = source._actBtn
      _tImgs = source._tImgs
      _detailInfo = source._detailInfo
      _monitorID = source._monitorID
      _hiddenDay = source._hiddenDay
      _tVideo = source._tVideo
      _tagName = source._tagName
      _tagNameURL = source._tagNameURL
      _tagNameWh = source._tagNameWh
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._isTuiguang) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._position) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._templateID) }()
        case 4: try { try decoder.decodeSingularInt32Field(value: &_storage._templateType) }()
        case 5: try { try decoder.decodeRepeatedMessageField(value: &_storage._actBtn) }()
        case 6: try { try decoder.decodeRepeatedMessageField(value: &_storage._tImgs) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._detailInfo) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._monitorID) }()
        case 9: try { try decoder.decodeSingularInt32Field(value: &_storage._hiddenDay) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._tVideo) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._tagName) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._tagNameURL) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._tagNameWh) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._isTuiguang != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._isTuiguang, fieldNumber: 1)
      }
      if !_storage._position.isEmpty {
        try visitor.visitSingularStringField(value: _storage._position, fieldNumber: 2)
      }
      if _storage._templateID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._templateID, fieldNumber: 3)
      }
      if _storage._templateType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._templateType, fieldNumber: 4)
      }
      if !_storage._actBtn.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._actBtn, fieldNumber: 5)
      }
      if !_storage._tImgs.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._tImgs, fieldNumber: 6)
      }
      try { if let v = _storage._detailInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if !_storage._monitorID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._monitorID, fieldNumber: 8)
      }
      if _storage._hiddenDay != 0 {
        try visitor.visitSingularInt32Field(value: _storage._hiddenDay, fieldNumber: 9)
      }
      try { if let v = _storage._tVideo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      if !_storage._tagName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tagName, fieldNumber: 11)
      }
      if !_storage._tagNameURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tagNameURL, fieldNumber: 12)
      }
      if !_storage._tagNameWh.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tagNameWh, fieldNumber: 13)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_TPointPost, rhs: Tieba_TPointPost) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._isTuiguang != rhs_storage._isTuiguang {return false}
        if _storage._position != rhs_storage._position {return false}
        if _storage._templateID != rhs_storage._templateID {return false}
        if _storage._templateType != rhs_storage._templateType {return false}
        if _storage._actBtn != rhs_storage._actBtn {return false}
        if _storage._tImgs != rhs_storage._tImgs {return false}
        if _storage._detailInfo != rhs_storage._detailInfo {return false}
        if _storage._monitorID != rhs_storage._monitorID {return false}
        if _storage._hiddenDay != rhs_storage._hiddenDay {return false}
        if _storage._tVideo != rhs_storage._tVideo {return false}
        if _storage._tagName != rhs_storage._tagName {return false}
        if _storage._tagNameURL != rhs_storage._tagNameURL {return false}
        if _storage._tagNameWh != rhs_storage._tagNameWh {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
