// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: UcCard.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_UcCard: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var icon: String = String()

  var doc: String = String()

  var jmp: String = String()

  var ucCards: [Tieba_UcCardInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_UcCard: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UcCard"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}icon\0\u{1}doc\0\u{1}jmp\0\u{3}uc_cards\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.icon) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.doc) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.jmp) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.ucCards) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.icon.isEmpty {
      try visitor.visitSingularStringField(value: self.icon, fieldNumber: 2)
    }
    if !self.doc.isEmpty {
      try visitor.visitSingularStringField(value: self.doc, fieldNumber: 3)
    }
    if !self.jmp.isEmpty {
      try visitor.visitSingularStringField(value: self.jmp, fieldNumber: 4)
    }
    if !self.ucCards.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ucCards, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_UcCard, rhs: Tieba_UcCard) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.icon != rhs.icon {return false}
    if lhs.doc != rhs.doc {return false}
    if lhs.jmp != rhs.jmp {return false}
    if lhs.ucCards != rhs.ucCards {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
