// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: UserPost/UserPostRequestData.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_UserPost_UserPostRequestData: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var uid: Int64 {
    get {_storage._uid}
    set {_uniqueStorage()._uid = newValue}
  }

  var rn: UInt32 {
    get {_storage._rn}
    set {_uniqueStorage()._rn = newValue}
  }

  var offset: UInt32 {
    get {_storage._offset}
    set {_uniqueStorage()._offset = newValue}
  }

  var isThread: UInt32 {
    get {_storage._isThread ?? 0}
    set {_uniqueStorage()._isThread = newValue}
  }
  /// Returns true if `isThread` has been explicitly set.
  var hasIsThread: Bool {_storage._isThread != nil}
  /// Clears the value of `isThread`. Subsequent reads from it will return its default value.
  mutating func clearIsThread() {_uniqueStorage()._isThread = nil}

  var needContent: UInt32 {
    get {_storage._needContent}
    set {_uniqueStorage()._needContent = newValue}
  }

  var forumID: UInt64 {
    get {_storage._forumID}
    set {_uniqueStorage()._forumID = newValue}
  }

  var beginTime: UInt32 {
    get {_storage._beginTime}
    set {_uniqueStorage()._beginTime = newValue}
  }

  var endTime: UInt32 {
    get {_storage._endTime}
    set {_uniqueStorage()._endTime = newValue}
  }

  var subtype: UInt32 {
    get {_storage._subtype ?? 0}
    set {_uniqueStorage()._subtype = newValue}
  }
  /// Returns true if `subtype` has been explicitly set.
  var hasSubtype: Bool {_storage._subtype != nil}
  /// Clears the value of `subtype`. Subsequent reads from it will return its default value.
  mutating func clearSubtype() {_uniqueStorage()._subtype = nil}

  var checkLogin: UInt32 {
    get {_storage._checkLogin}
    set {_uniqueStorage()._checkLogin = newValue}
  }

  var ipStr: String {
    get {_storage._ipStr}
    set {_uniqueStorage()._ipStr = newValue}
  }

  var ipInt: UInt32 {
    get {_storage._ipInt}
    set {_uniqueStorage()._ipInt = newValue}
  }

  var moduleName: String {
    get {_storage._moduleName}
    set {_uniqueStorage()._moduleName = newValue}
  }

  var stType: UInt32 {
    get {_storage._stType}
    set {_uniqueStorage()._stType = newValue}
  }

  var stParam: UInt32 {
    get {_storage._stParam}
    set {_uniqueStorage()._stParam = newValue}
  }

  var smileGrade: UInt32 {
    get {_storage._smileGrade}
    set {_uniqueStorage()._smileGrade = newValue}
  }

  var supportNoun: UInt32 {
    get {_storage._supportNoun}
    set {_uniqueStorage()._supportNoun = newValue}
  }

  var login: UInt32 {
    get {_storage._login}
    set {_uniqueStorage()._login = newValue}
  }

  var userID: Int64 {
    get {_storage._userID}
    set {_uniqueStorage()._userID = newValue}
  }

  var userName: String {
    get {_storage._userName}
    set {_uniqueStorage()._userName = newValue}
  }

  var noUn: UInt32 {
    get {_storage._noUn}
    set {_uniqueStorage()._noUn = newValue}
  }

  var portrait: String {
    get {_storage._portrait}
    set {_uniqueStorage()._portrait = newValue}
  }

  var mobile: String {
    get {_storage._mobile}
    set {_uniqueStorage()._mobile = newValue}
  }

  var email: String {
    get {_storage._email}
    set {_uniqueStorage()._email = newValue}
  }

  var cookie: String {
    get {_storage._cookie}
    set {_uniqueStorage()._cookie = newValue}
  }

  var pn: UInt32 {
    get {_storage._pn}
    set {_uniqueStorage()._pn = newValue}
  }

  var common: Tieba_CommonRequest {
    get {_storage._common ?? Tieba_CommonRequest()}
    set {_uniqueStorage()._common = newValue}
  }
  /// Returns true if `common` has been explicitly set.
  var hasCommon: Bool {_storage._common != nil}
  /// Clears the value of `common`. Subsequent reads from it will return its default value.
  mutating func clearCommon() {_uniqueStorage()._common = nil}

  var isTwzhibo: UInt32 {
    get {_storage._isTwzhibo}
    set {_uniqueStorage()._isTwzhibo = newValue}
  }

  var scrW: Int32 {
    get {_storage._scrW}
    set {_uniqueStorage()._scrW = newValue}
  }

  var scrH: Int32 {
    get {_storage._scrH}
    set {_uniqueStorage()._scrH = newValue}
  }

  var scrDip: Double {
    get {_storage._scrDip}
    set {_uniqueStorage()._scrDip = newValue}
  }

  var qType: Int32 {
    get {_storage._qType}
    set {_uniqueStorage()._qType = newValue}
  }

  var isViewCard: Int32 {
    get {_storage._isViewCard ?? 0}
    set {_uniqueStorage()._isViewCard = newValue}
  }
  /// Returns true if `isViewCard` has been explicitly set.
  var hasIsViewCard: Bool {_storage._isViewCard != nil}
  /// Clears the value of `isViewCard`. Subsequent reads from it will return its default value.
  mutating func clearIsViewCard() {_uniqueStorage()._isViewCard = nil}

  var lastThreadTime: UInt32 {
    get {_storage._lastThreadTime}
    set {_uniqueStorage()._lastThreadTime = newValue}
  }

  var workTabID: UInt32 {
    get {_storage._workTabID}
    set {_uniqueStorage()._workTabID = newValue}
  }

  var type: UInt32 {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  var fromType: UInt32 {
    get {_storage._fromType}
    set {_uniqueStorage()._fromType = newValue}
  }

  var beginThreadID: UInt64 {
    get {_storage._beginThreadID}
    set {_uniqueStorage()._beginThreadID = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.userPost"

nonisolated extension Tieba_UserPost_UserPostRequestData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserPostRequestData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uid\0\u{1}rn\0\u{1}offset\0\u{3}is_thread\0\u{3}need_content\0\u{3}forum_id\0\u{3}begin_time\0\u{3}end_time\0\u{1}subtype\0\u{3}check_login\0\u{3}ip_str\0\u{3}ip_int\0\u{3}module_name\0\u{3}st_type\0\u{3}st_param\0\u{3}smile_grade\0\u{3}support_noun\0\u{1}login\0\u{3}user_id\0\u{3}user_name\0\u{3}no_un\0\u{1}portrait\0\u{1}mobile\0\u{1}email\0\u{1}cookie\0\u{1}pn\0\u{1}common\0\u{3}is_twzhibo\0\u{3}scr_w\0\u{3}scr_h\0\u{3}scr_dip\0\u{3}q_type\0\u{3}is_view_card\0\u{3}last_thread_time\0\u{3}work_tab_id\0\u{1}type\0\u{3}from_type\0\u{3}begin_thread_id\0")

  fileprivate class _StorageClass {
    var _uid: Int64 = 0
    var _rn: UInt32 = 0
    var _offset: UInt32 = 0
    var _isThread: UInt32? = nil
    var _needContent: UInt32 = 0
    var _forumID: UInt64 = 0
    var _beginTime: UInt32 = 0
    var _endTime: UInt32 = 0
    var _subtype: UInt32? = nil
    var _checkLogin: UInt32 = 0
    var _ipStr: String = String()
    var _ipInt: UInt32 = 0
    var _moduleName: String = String()
    var _stType: UInt32 = 0
    var _stParam: UInt32 = 0
    var _smileGrade: UInt32 = 0
    var _supportNoun: UInt32 = 0
    var _login: UInt32 = 0
    var _userID: Int64 = 0
    var _userName: String = String()
    var _noUn: UInt32 = 0
    var _portrait: String = String()
    var _mobile: String = String()
    var _email: String = String()
    var _cookie: String = String()
    var _pn: UInt32 = 0
    var _common: Tieba_CommonRequest? = nil
    var _isTwzhibo: UInt32 = 0
    var _scrW: Int32 = 0
    var _scrH: Int32 = 0
    var _scrDip: Double = 0
    var _qType: Int32 = 0
    var _isViewCard: Int32? = nil
    var _lastThreadTime: UInt32 = 0
    var _workTabID: UInt32 = 0
    var _type: UInt32 = 0
    var _fromType: UInt32 = 0
    var _beginThreadID: UInt64 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _uid = source._uid
      _rn = source._rn
      _offset = source._offset
      _isThread = source._isThread
      _needContent = source._needContent
      _forumID = source._forumID
      _beginTime = source._beginTime
      _endTime = source._endTime
      _subtype = source._subtype
      _checkLogin = source._checkLogin
      _ipStr = source._ipStr
      _ipInt = source._ipInt
      _moduleName = source._moduleName
      _stType = source._stType
      _stParam = source._stParam
      _smileGrade = source._smileGrade
      _supportNoun = source._supportNoun
      _login = source._login
      _userID = source._userID
      _userName = source._userName
      _noUn = source._noUn
      _portrait = source._portrait
      _mobile = source._mobile
      _email = source._email
      _cookie = source._cookie
      _pn = source._pn
      _common = source._common
      _isTwzhibo = source._isTwzhibo
      _scrW = source._scrW
      _scrH = source._scrH
      _scrDip = source._scrDip
      _qType = source._qType
      _isViewCard = source._isViewCard
      _lastThreadTime = source._lastThreadTime
      _workTabID = source._workTabID
      _type = source._type
      _fromType = source._fromType
      _beginThreadID = source._beginThreadID
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt64Field(value: &_storage._uid) }()
        case 2: try { try decoder.decodeSingularUInt32Field(value: &_storage._rn) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._offset) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._isThread) }()
        case 5: try { try decoder.decodeSingularUInt32Field(value: &_storage._needContent) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._forumID) }()
        case 7: try { try decoder.decodeSingularUInt32Field(value: &_storage._beginTime) }()
        case 8: try { try decoder.decodeSingularUInt32Field(value: &_storage._endTime) }()
        case 9: try { try decoder.decodeSingularUInt32Field(value: &_storage._subtype) }()
        case 10: try { try decoder.decodeSingularUInt32Field(value: &_storage._checkLogin) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._ipStr) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._ipInt) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._moduleName) }()
        case 14: try { try decoder.decodeSingularUInt32Field(value: &_storage._stType) }()
        case 15: try { try decoder.decodeSingularUInt32Field(value: &_storage._stParam) }()
        case 16: try { try decoder.decodeSingularUInt32Field(value: &_storage._smileGrade) }()
        case 17: try { try decoder.decodeSingularUInt32Field(value: &_storage._supportNoun) }()
        case 18: try { try decoder.decodeSingularUInt32Field(value: &_storage._login) }()
        case 19: try { try decoder.decodeSingularInt64Field(value: &_storage._userID) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._userName) }()
        case 21: try { try decoder.decodeSingularUInt32Field(value: &_storage._noUn) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._portrait) }()
        case 23: try { try decoder.decodeSingularStringField(value: &_storage._mobile) }()
        case 24: try { try decoder.decodeSingularStringField(value: &_storage._email) }()
        case 25: try { try decoder.decodeSingularStringField(value: &_storage._cookie) }()
        case 26: try { try decoder.decodeSingularUInt32Field(value: &_storage._pn) }()
        case 27: try { try decoder.decodeSingularMessageField(value: &_storage._common) }()
        case 28: try { try decoder.decodeSingularUInt32Field(value: &_storage._isTwzhibo) }()
        case 29: try { try decoder.decodeSingularInt32Field(value: &_storage._scrW) }()
        case 30: try { try decoder.decodeSingularInt32Field(value: &_storage._scrH) }()
        case 31: try { try decoder.decodeSingularDoubleField(value: &_storage._scrDip) }()
        case 32: try { try decoder.decodeSingularInt32Field(value: &_storage._qType) }()
        case 33: try { try decoder.decodeSingularInt32Field(value: &_storage._isViewCard) }()
        case 34: try { try decoder.decodeSingularUInt32Field(value: &_storage._lastThreadTime) }()
        case 35: try { try decoder.decodeSingularUInt32Field(value: &_storage._workTabID) }()
        case 36: try { try decoder.decodeSingularUInt32Field(value: &_storage._type) }()
        case 37: try { try decoder.decodeSingularUInt32Field(value: &_storage._fromType) }()
        case 38: try { try decoder.decodeSingularUInt64Field(value: &_storage._beginThreadID) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._uid != 0 {
        try visitor.visitSingularInt64Field(value: _storage._uid, fieldNumber: 1)
      }
      if _storage._rn != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._rn, fieldNumber: 2)
      }
      if _storage._offset != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._offset, fieldNumber: 3)
      }
      try { if let v = _storage._isThread {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
      } }()
      if _storage._needContent != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._needContent, fieldNumber: 5)
      }
      if _storage._forumID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._forumID, fieldNumber: 6)
      }
      if _storage._beginTime != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._beginTime, fieldNumber: 7)
      }
      if _storage._endTime != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._endTime, fieldNumber: 8)
      }
      try { if let v = _storage._subtype {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 9)
      } }()
      if _storage._checkLogin != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._checkLogin, fieldNumber: 10)
      }
      if !_storage._ipStr.isEmpty {
        try visitor.visitSingularStringField(value: _storage._ipStr, fieldNumber: 11)
      }
      if _storage._ipInt != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._ipInt, fieldNumber: 12)
      }
      if !_storage._moduleName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._moduleName, fieldNumber: 13)
      }
      if _storage._stType != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._stType, fieldNumber: 14)
      }
      if _storage._stParam != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._stParam, fieldNumber: 15)
      }
      if _storage._smileGrade != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._smileGrade, fieldNumber: 16)
      }
      if _storage._supportNoun != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._supportNoun, fieldNumber: 17)
      }
      if _storage._login != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._login, fieldNumber: 18)
      }
      if _storage._userID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._userID, fieldNumber: 19)
      }
      if !_storage._userName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._userName, fieldNumber: 20)
      }
      if _storage._noUn != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._noUn, fieldNumber: 21)
      }
      if !_storage._portrait.isEmpty {
        try visitor.visitSingularStringField(value: _storage._portrait, fieldNumber: 22)
      }
      if !_storage._mobile.isEmpty {
        try visitor.visitSingularStringField(value: _storage._mobile, fieldNumber: 23)
      }
      if !_storage._email.isEmpty {
        try visitor.visitSingularStringField(value: _storage._email, fieldNumber: 24)
      }
      if !_storage._cookie.isEmpty {
        try visitor.visitSingularStringField(value: _storage._cookie, fieldNumber: 25)
      }
      if _storage._pn != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._pn, fieldNumber: 26)
      }
      try { if let v = _storage._common {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 27)
      } }()
      if _storage._isTwzhibo != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._isTwzhibo, fieldNumber: 28)
      }
      if _storage._scrW != 0 {
        try visitor.visitSingularInt32Field(value: _storage._scrW, fieldNumber: 29)
      }
      if _storage._scrH != 0 {
        try visitor.visitSingularInt32Field(value: _storage._scrH, fieldNumber: 30)
      }
      if _storage._scrDip.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._scrDip, fieldNumber: 31)
      }
      if _storage._qType != 0 {
        try visitor.visitSingularInt32Field(value: _storage._qType, fieldNumber: 32)
      }
      try { if let v = _storage._isViewCard {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 33)
      } }()
      if _storage._lastThreadTime != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._lastThreadTime, fieldNumber: 34)
      }
      if _storage._workTabID != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._workTabID, fieldNumber: 35)
      }
      if _storage._type != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._type, fieldNumber: 36)
      }
      if _storage._fromType != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._fromType, fieldNumber: 37)
      }
      if _storage._beginThreadID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._beginThreadID, fieldNumber: 38)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_UserPost_UserPostRequestData, rhs: Tieba_UserPost_UserPostRequestData) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._uid != rhs_storage._uid {return false}
        if _storage._rn != rhs_storage._rn {return false}
        if _storage._offset != rhs_storage._offset {return false}
        if _storage._isThread != rhs_storage._isThread {return false}
        if _storage._needContent != rhs_storage._needContent {return false}
        if _storage._forumID != rhs_storage._forumID {return false}
        if _storage._beginTime != rhs_storage._beginTime {return false}
        if _storage._endTime != rhs_storage._endTime {return false}
        if _storage._subtype != rhs_storage._subtype {return false}
        if _storage._checkLogin != rhs_storage._checkLogin {return false}
        if _storage._ipStr != rhs_storage._ipStr {return false}
        if _storage._ipInt != rhs_storage._ipInt {return false}
        if _storage._moduleName != rhs_storage._moduleName {return false}
        if _storage._stType != rhs_storage._stType {return false}
        if _storage._stParam != rhs_storage._stParam {return false}
        if _storage._smileGrade != rhs_storage._smileGrade {return false}
        if _storage._supportNoun != rhs_storage._supportNoun {return false}
        if _storage._login != rhs_storage._login {return false}
        if _storage._userID != rhs_storage._userID {return false}
        if _storage._userName != rhs_storage._userName {return false}
        if _storage._noUn != rhs_storage._noUn {return false}
        if _storage._portrait != rhs_storage._portrait {return false}
        if _storage._mobile != rhs_storage._mobile {return false}
        if _storage._email != rhs_storage._email {return false}
        if _storage._cookie != rhs_storage._cookie {return false}
        if _storage._pn != rhs_storage._pn {return false}
        if _storage._common != rhs_storage._common {return false}
        if _storage._isTwzhibo != rhs_storage._isTwzhibo {return false}
        if _storage._scrW != rhs_storage._scrW {return false}
        if _storage._scrH != rhs_storage._scrH {return false}
        if _storage._scrDip != rhs_storage._scrDip {return false}
        if _storage._qType != rhs_storage._qType {return false}
        if _storage._isViewCard != rhs_storage._isViewCard {return false}
        if _storage._lastThreadTime != rhs_storage._lastThreadTime {return false}
        if _storage._workTabID != rhs_storage._workTabID {return false}
        if _storage._type != rhs_storage._type {return false}
        if _storage._fromType != rhs_storage._fromType {return false}
        if _storage._beginThreadID != rhs_storage._beginThreadID {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
