// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ZhiBoInfoTW.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_ZhiBoInfoTW: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var threadID: UInt64 {
    get {_storage._threadID}
    set {_uniqueStorage()._threadID = newValue}
  }

  var livecoverSrc: String {
    get {_storage._livecoverSrc}
    set {_uniqueStorage()._livecoverSrc = newValue}
  }

  var livecoverSrcBsize: String {
    get {_storage._livecoverSrcBsize}
    set {_uniqueStorage()._livecoverSrcBsize = newValue}
  }

  var postNum: UInt32 {
    get {_storage._postNum}
    set {_uniqueStorage()._postNum = newValue}
  }

  var replyNum: UInt32 {
    get {_storage._replyNum}
    set {_uniqueStorage()._replyNum = newValue}
  }

  var zan: Tieba_Zan {
    get {_storage._zan ?? Tieba_Zan()}
    set {_uniqueStorage()._zan = newValue}
  }
  /// Returns true if `zan` has been explicitly set.
  var hasZan: Bool {_storage._zan != nil}
  /// Clears the value of `zan`. Subsequent reads from it will return its default value.
  mutating func clearZan() {_uniqueStorage()._zan = nil}

  var forumName: String {
    get {_storage._forumName}
    set {_uniqueStorage()._forumName = newValue}
  }

  var forumID: UInt64 {
    get {_storage._forumID}
    set {_uniqueStorage()._forumID = newValue}
  }

  var lastModifiedTime: UInt64 {
    get {_storage._lastModifiedTime}
    set {_uniqueStorage()._lastModifiedTime = newValue}
  }

  var title: String {
    get {_storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  var content: String {
    get {_storage._content}
    set {_uniqueStorage()._content = newValue}
  }

  var user: Tieba_User {
    get {_storage._user ?? Tieba_User()}
    set {_uniqueStorage()._user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {_storage._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {_uniqueStorage()._user = nil}

  var hotTwInfo: Tieba_HotTWThreadInfo {
    get {_storage._hotTwInfo ?? Tieba_HotTWThreadInfo()}
    set {_uniqueStorage()._hotTwInfo = newValue}
  }
  /// Returns true if `hotTwInfo` has been explicitly set.
  var hasHotTwInfo: Bool {_storage._hotTwInfo != nil}
  /// Clears the value of `hotTwInfo`. Subsequent reads from it will return its default value.
  mutating func clearHotTwInfo() {_uniqueStorage()._hotTwInfo = nil}

  var labelInfo: [Tieba_LabelInfo] {
    get {_storage._labelInfo}
    set {_uniqueStorage()._labelInfo = newValue}
  }

  var livecoverSrcStatus: String {
    get {_storage._livecoverSrcStatus}
    set {_uniqueStorage()._livecoverSrcStatus = newValue}
  }

  var noticeInfo: Tieba_NoticeInfo {
    get {_storage._noticeInfo ?? Tieba_NoticeInfo()}
    set {_uniqueStorage()._noticeInfo = newValue}
  }
  /// Returns true if `noticeInfo` has been explicitly set.
  var hasNoticeInfo: Bool {_storage._noticeInfo != nil}
  /// Clears the value of `noticeInfo`. Subsequent reads from it will return its default value.
  mutating func clearNoticeInfo() {_uniqueStorage()._noticeInfo = nil}

  var isHeadline: Int32 {
    get {_storage._isHeadline}
    set {_uniqueStorage()._isHeadline = newValue}
  }

  var livecoverStatus: Tieba_LiveCoverStatus {
    get {_storage._livecoverStatus ?? Tieba_LiveCoverStatus()}
    set {_uniqueStorage()._livecoverStatus = newValue}
  }
  /// Returns true if `livecoverStatus` has been explicitly set.
  var hasLivecoverStatus: Bool {_storage._livecoverStatus != nil}
  /// Clears the value of `livecoverStatus`. Subsequent reads from it will return its default value.
  mutating func clearLivecoverStatus() {_uniqueStorage()._livecoverStatus = nil}

  var freqNum: UInt32 {
    get {_storage._freqNum}
    set {_uniqueStorage()._freqNum = newValue}
  }

  var copythreadRemind: UInt32 {
    get {_storage._copythreadRemind}
    set {_uniqueStorage()._copythreadRemind = newValue}
  }

  var isCopytwzhibo: UInt32 {
    get {_storage._isCopytwzhibo}
    set {_uniqueStorage()._isCopytwzhibo = newValue}
  }

  var fieldEx: String {
    get {_storage._fieldEx}
    set {_uniqueStorage()._fieldEx = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_ZhiBoInfoTW: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ZhiBoInfoTW"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}thread_id\0\u{3}livecover_src\0\u{3}livecover_src_bsize\0\u{3}post_num\0\u{3}reply_num\0\u{1}zan\0\u{3}forum_name\0\u{3}forum_id\0\u{3}last_modified_time\0\u{1}title\0\u{1}content\0\u{1}user\0\u{3}hot_tw_info\0\u{1}labelInfo\0\u{3}livecover_src_status\0\u{3}notice_info\0\u{3}is_headline\0\u{3}livecover_status\0\u{3}freq_num\0\u{3}copythread_remind\0\u{3}is_copytwzhibo\0\u{3}field_ex\0")

  fileprivate class _StorageClass {
    var _threadID: UInt64 = 0
    var _livecoverSrc: String = String()
    var _livecoverSrcBsize: String = String()
    var _postNum: UInt32 = 0
    var _replyNum: UInt32 = 0
    var _zan: Tieba_Zan? = nil
    var _forumName: String = String()
    var _forumID: UInt64 = 0
    var _lastModifiedTime: UInt64 = 0
    var _title: String = String()
    var _content: String = String()
    var _user: Tieba_User? = nil
    var _hotTwInfo: Tieba_HotTWThreadInfo? = nil
    var _labelInfo: [Tieba_LabelInfo] = []
    var _livecoverSrcStatus: String = String()
    var _noticeInfo: Tieba_NoticeInfo? = nil
    var _isHeadline: Int32 = 0
    var _livecoverStatus: Tieba_LiveCoverStatus? = nil
    var _freqNum: UInt32 = 0
    var _copythreadRemind: UInt32 = 0
    var _isCopytwzhibo: UInt32 = 0
    var _fieldEx: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _threadID = source._threadID
      _livecoverSrc = source._livecoverSrc
      _livecoverSrcBsize = source._livecoverSrcBsize
      _postNum = source._postNum
      _replyNum = source._replyNum
      _zan = source._zan
      _forumName = source._forumName
      _forumID = source._forumID
      _lastModifiedTime = source._lastModifiedTime
      _title = source._title
      _content = source._content
      _user = source._user
      _hotTwInfo = source._hotTwInfo
      _labelInfo = source._labelInfo
      _livecoverSrcStatus = source._livecoverSrcStatus
      _noticeInfo = source._noticeInfo
      _isHeadline = source._isHeadline
      _livecoverStatus = source._livecoverStatus
      _freqNum = source._freqNum
      _copythreadRemind = source._copythreadRemind
      _isCopytwzhibo = source._isCopytwzhibo
      _fieldEx = source._fieldEx
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._threadID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._livecoverSrc) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._livecoverSrcBsize) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._postNum) }()
        case 5: try { try decoder.decodeSingularUInt32Field(value: &_storage._replyNum) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._zan) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._forumName) }()
        case 8: try { try decoder.decodeSingularUInt64Field(value: &_storage._forumID) }()
        case 9: try { try decoder.decodeSingularUInt64Field(value: &_storage._lastModifiedTime) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._content) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._user) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._hotTwInfo) }()
        case 14: try { try decoder.decodeRepeatedMessageField(value: &_storage._labelInfo) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._livecoverSrcStatus) }()
        case 16: try { try decoder.decodeSingularMessageField(value: &_storage._noticeInfo) }()
        case 17: try { try decoder.decodeSingularInt32Field(value: &_storage._isHeadline) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._livecoverStatus) }()
        case 19: try { try decoder.decodeSingularUInt32Field(value: &_storage._freqNum) }()
        case 20: try { try decoder.decodeSingularUInt32Field(value: &_storage._copythreadRemind) }()
        case 21: try { try decoder.decodeSingularUInt32Field(value: &_storage._isCopytwzhibo) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._fieldEx) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._threadID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._threadID, fieldNumber: 1)
      }
      if !_storage._livecoverSrc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._livecoverSrc, fieldNumber: 2)
      }
      if !_storage._livecoverSrcBsize.isEmpty {
        try visitor.visitSingularStringField(value: _storage._livecoverSrcBsize, fieldNumber: 3)
      }
      if _storage._postNum != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._postNum, fieldNumber: 4)
      }
      if _storage._replyNum != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._replyNum, fieldNumber: 5)
      }
      try { if let v = _storage._zan {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if !_storage._forumName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._forumName, fieldNumber: 7)
      }
      if _storage._forumID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._forumID, fieldNumber: 8)
      }
      if _storage._lastModifiedTime != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._lastModifiedTime, fieldNumber: 9)
      }
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 10)
      }
      if !_storage._content.isEmpty {
        try visitor.visitSingularStringField(value: _storage._content, fieldNumber: 11)
      }
      try { if let v = _storage._user {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._hotTwInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      if !_storage._labelInfo.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._labelInfo, fieldNumber: 14)
      }
      if !_storage._livecoverSrcStatus.isEmpty {
        try visitor.visitSingularStringField(value: _storage._livecoverSrcStatus, fieldNumber: 15)
      }
      try { if let v = _storage._noticeInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
      } }()
      if _storage._isHeadline != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isHeadline, fieldNumber: 17)
      }
      try { if let v = _storage._livecoverStatus {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
      if _storage._freqNum != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._freqNum, fieldNumber: 19)
      }
      if _storage._copythreadRemind != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._copythreadRemind, fieldNumber: 20)
      }
      if _storage._isCopytwzhibo != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._isCopytwzhibo, fieldNumber: 21)
      }
      if !_storage._fieldEx.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fieldEx, fieldNumber: 22)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_ZhiBoInfoTW, rhs: Tieba_ZhiBoInfoTW) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._threadID != rhs_storage._threadID {return false}
        if _storage._livecoverSrc != rhs_storage._livecoverSrc {return false}
        if _storage._livecoverSrcBsize != rhs_storage._livecoverSrcBsize {return false}
        if _storage._postNum != rhs_storage._postNum {return false}
        if _storage._replyNum != rhs_storage._replyNum {return false}
        if _storage._zan != rhs_storage._zan {return false}
        if _storage._forumName != rhs_storage._forumName {return false}
        if _storage._forumID != rhs_storage._forumID {return false}
        if _storage._lastModifiedTime != rhs_storage._lastModifiedTime {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._content != rhs_storage._content {return false}
        if _storage._user != rhs_storage._user {return false}
        if _storage._hotTwInfo != rhs_storage._hotTwInfo {return false}
        if _storage._labelInfo != rhs_storage._labelInfo {return false}
        if _storage._livecoverSrcStatus != rhs_storage._livecoverSrcStatus {return false}
        if _storage._noticeInfo != rhs_storage._noticeInfo {return false}
        if _storage._isHeadline != rhs_storage._isHeadline {return false}
        if _storage._livecoverStatus != rhs_storage._livecoverStatus {return false}
        if _storage._freqNum != rhs_storage._freqNum {return false}
        if _storage._copythreadRemind != rhs_storage._copythreadRemind {return false}
        if _storage._isCopytwzhibo != rhs_storage._isCopytwzhibo {return false}
        if _storage._fieldEx != rhs_storage._fieldEx {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
