// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: FeedForumInfo.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_FeedForumInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var forumID: UInt64 = 0

  var forumName: String = String()

  var memberCount: Int32 = 0

  var postNum: Int32 = 0

  var avatar: String = String()

  var reason: String = String()

  var pos: Int32 = 0

  var isLike: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_FeedForumInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeedForumInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}forum_id\0\u{3}forum_name\0\u{3}member_count\0\u{3}post_num\0\u{1}avatar\0\u{1}reason\0\u{1}pos\0\u{3}is_like\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.forumID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.forumName) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.memberCount) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.postNum) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.avatar) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.reason) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.pos) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.isLike) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.forumID != 0 {
      try visitor.visitSingularUInt64Field(value: self.forumID, fieldNumber: 1)
    }
    if !self.forumName.isEmpty {
      try visitor.visitSingularStringField(value: self.forumName, fieldNumber: 2)
    }
    if self.memberCount != 0 {
      try visitor.visitSingularInt32Field(value: self.memberCount, fieldNumber: 3)
    }
    if self.postNum != 0 {
      try visitor.visitSingularInt32Field(value: self.postNum, fieldNumber: 4)
    }
    if !self.avatar.isEmpty {
      try visitor.visitSingularStringField(value: self.avatar, fieldNumber: 5)
    }
    if !self.reason.isEmpty {
      try visitor.visitSingularStringField(value: self.reason, fieldNumber: 6)
    }
    if self.pos != 0 {
      try visitor.visitSingularInt32Field(value: self.pos, fieldNumber: 7)
    }
    if self.isLike != 0 {
      try visitor.visitSingularInt32Field(value: self.isLike, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_FeedForumInfo, rhs: Tieba_FeedForumInfo) -> Bool {
    if lhs.forumID != rhs.forumID {return false}
    if lhs.forumName != rhs.forumName {return false}
    if lhs.memberCount != rhs.memberCount {return false}
    if lhs.postNum != rhs.postNum {return false}
    if lhs.avatar != rhs.avatar {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.pos != rhs.pos {return false}
    if lhs.isLike != rhs.isLike {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
