// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: GetForumDetail/BazhuUniversity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_GetForumDetail_BazhuUniversity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var entrance: [Tieba_GetForumDetail_UniversityInfo] = []

  var banner: [Tieba_GetForumDetail_UniversityInfo] = []

  var tab: [Tieba_GetForumDetail_UniversityTabInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.getForumDetail"

nonisolated extension Tieba_GetForumDetail_BazhuUniversity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BazhuUniversity"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entrance\0\u{1}banner\0\u{1}tab\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entrance) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.banner) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.tab) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entrance.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entrance, fieldNumber: 1)
    }
    if !self.banner.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.banner, fieldNumber: 2)
    }
    if !self.tab.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tab, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_GetForumDetail_BazhuUniversity, rhs: Tieba_GetForumDetail_BazhuUniversity) -> Bool {
    if lhs.entrance != rhs.entrance {return false}
    if lhs.banner != rhs.banner {return false}
    if lhs.tab != rhs.tab {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
