// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: GradePoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_GradePoint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pointName: String = String()

  var pointType: Int32 = 0

  var currentPoint: Int32 = 0

  var nextPoint: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_GradePoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GradePoint"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}point_name\0\u{3}point_type\0\u{3}current_point\0\u{3}next_point\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pointName) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.pointType) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.currentPoint) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.nextPoint) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pointName.isEmpty {
      try visitor.visitSingularStringField(value: self.pointName, fieldNumber: 1)
    }
    if self.pointType != 0 {
      try visitor.visitSingularInt32Field(value: self.pointType, fieldNumber: 2)
    }
    if self.currentPoint != 0 {
      try visitor.visitSingularInt32Field(value: self.currentPoint, fieldNumber: 3)
    }
    if self.nextPoint != 0 {
      try visitor.visitSingularInt32Field(value: self.nextPoint, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_GradePoint, rhs: Tieba_GradePoint) -> Bool {
    if lhs.pointName != rhs.pointName {return false}
    if lhs.pointType != rhs.pointType {return false}
    if lhs.currentPoint != rhs.currentPoint {return false}
    if lhs.nextPoint != rhs.nextPoint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
