// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: GraffitiRankItem.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_GraffitiRankItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var gid: Int64 = 0

  var url: String = String()

  var voteCount: Int64 = 0

  var isVote: Int32 = 0

  var uid: Int64 = 0

  var picID: String = String()

  var gType: Int32 = 0

  var thumbURL: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_GraffitiRankItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GraffitiRankItem"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}gid\0\u{1}url\0\u{3}vote_count\0\u{3}is_vote\0\u{1}uid\0\u{3}pic_id\0\u{3}g_type\0\u{3}thumb_url\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.gid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.voteCount) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.isVote) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.uid) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.picID) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.gType) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.thumbURL) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.gid != 0 {
      try visitor.visitSingularInt64Field(value: self.gid, fieldNumber: 1)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 2)
    }
    if self.voteCount != 0 {
      try visitor.visitSingularInt64Field(value: self.voteCount, fieldNumber: 3)
    }
    if self.isVote != 0 {
      try visitor.visitSingularInt32Field(value: self.isVote, fieldNumber: 4)
    }
    if self.uid != 0 {
      try visitor.visitSingularInt64Field(value: self.uid, fieldNumber: 5)
    }
    if !self.picID.isEmpty {
      try visitor.visitSingularStringField(value: self.picID, fieldNumber: 6)
    }
    if self.gType != 0 {
      try visitor.visitSingularInt32Field(value: self.gType, fieldNumber: 7)
    }
    if !self.thumbURL.isEmpty {
      try visitor.visitSingularStringField(value: self.thumbURL, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_GraffitiRankItem, rhs: Tieba_GraffitiRankItem) -> Bool {
    if lhs.gid != rhs.gid {return false}
    if lhs.url != rhs.url {return false}
    if lhs.voteCount != rhs.voteCount {return false}
    if lhs.isVote != rhs.isVote {return false}
    if lhs.uid != rhs.uid {return false}
    if lhs.picID != rhs.picID {return false}
    if lhs.gType != rhs.gType {return false}
    if lhs.thumbURL != rhs.thumbURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
