// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: UserPost/UserPostResponseData.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_UserPost_UserPostResponseData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var postList: [Tieba_PostInfoList] = []

  var hidePost: UInt32 = 0

  var time: UInt64 = 0

  var ctime: UInt64 = 0

  var logid: UInt64 = 0

  var maskType: Int32 = 0

  var viewCardNum: Int32 = 0

  var reddotDeletedThread: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba.userPost"

nonisolated extension Tieba_UserPost_UserPostResponseData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserPostResponseData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}post_list\0\u{3}hide_post\0\u{1}time\0\u{1}ctime\0\u{1}logid\0\u{3}mask_type\0\u{3}view_card_num\0\u{3}reddot_deleted_thread\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.postList) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.hidePost) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.time) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.ctime) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.logid) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.maskType) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.viewCardNum) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.reddotDeletedThread) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.postList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.postList, fieldNumber: 1)
    }
    if self.hidePost != 0 {
      try visitor.visitSingularUInt32Field(value: self.hidePost, fieldNumber: 2)
    }
    if self.time != 0 {
      try visitor.visitSingularUInt64Field(value: self.time, fieldNumber: 3)
    }
    if self.ctime != 0 {
      try visitor.visitSingularUInt64Field(value: self.ctime, fieldNumber: 4)
    }
    if self.logid != 0 {
      try visitor.visitSingularUInt64Field(value: self.logid, fieldNumber: 5)
    }
    if self.maskType != 0 {
      try visitor.visitSingularInt32Field(value: self.maskType, fieldNumber: 6)
    }
    if self.viewCardNum != 0 {
      try visitor.visitSingularInt32Field(value: self.viewCardNum, fieldNumber: 7)
    }
    if self.reddotDeletedThread != 0 {
      try visitor.visitSingularInt32Field(value: self.reddotDeletedThread, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_UserPost_UserPostResponseData, rhs: Tieba_UserPost_UserPostResponseData) -> Bool {
    if lhs.postList != rhs.postList {return false}
    if lhs.hidePost != rhs.hidePost {return false}
    if lhs.time != rhs.time {return false}
    if lhs.ctime != rhs.ctime {return false}
    if lhs.logid != rhs.logid {return false}
    if lhs.maskType != rhs.maskType {return false}
    if lhs.viewCardNum != rhs.viewCardNum {return false}
    if lhs.reddotDeletedThread != rhs.reddotDeletedThread {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
