// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: YyExt.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Tieba_YyExt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sid: String = String()

  var ssid: String = String()

  var templateID: String = String()

  var yyUid: String = String()

  var isYyGame: Int32 = 0

  var streamInfo: String = String()

  var rankShow: String = String()

  var iconURL: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tieba"

nonisolated extension Tieba_YyExt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".YyExt"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sid\0\u{1}ssid\0\u{3}template_id\0\u{3}yy_uid\0\u{3}is_yy_game\0\u{3}stream_info\0\u{3}rank_show\0\u{3}icon_url\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.ssid) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.templateID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.yyUid) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.isYyGame) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.streamInfo) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.rankShow) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.iconURL) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sid.isEmpty {
      try visitor.visitSingularStringField(value: self.sid, fieldNumber: 1)
    }
    if !self.ssid.isEmpty {
      try visitor.visitSingularStringField(value: self.ssid, fieldNumber: 2)
    }
    if !self.templateID.isEmpty {
      try visitor.visitSingularStringField(value: self.templateID, fieldNumber: 3)
    }
    if !self.yyUid.isEmpty {
      try visitor.visitSingularStringField(value: self.yyUid, fieldNumber: 4)
    }
    if self.isYyGame != 0 {
      try visitor.visitSingularInt32Field(value: self.isYyGame, fieldNumber: 5)
    }
    if !self.streamInfo.isEmpty {
      try visitor.visitSingularStringField(value: self.streamInfo, fieldNumber: 6)
    }
    if !self.rankShow.isEmpty {
      try visitor.visitSingularStringField(value: self.rankShow, fieldNumber: 7)
    }
    if !self.iconURL.isEmpty {
      try visitor.visitSingularStringField(value: self.iconURL, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tieba_YyExt, rhs: Tieba_YyExt) -> Bool {
    if lhs.sid != rhs.sid {return false}
    if lhs.ssid != rhs.ssid {return false}
    if lhs.templateID != rhs.templateID {return false}
    if lhs.yyUid != rhs.yyUid {return false}
    if lhs.isYyGame != rhs.isYyGame {return false}
    if lhs.streamInfo != rhs.streamInfo {return false}
    if lhs.rankShow != rhs.rankShow {return false}
    if lhs.iconURL != rhs.iconURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
